import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

const tabEnter = stylex.keyframes({
  from: { opacity: 0, transform: "translateX(6px)" },
  to: { opacity: 1, transform: "translateX(0)" },
})
const tabFade = stylex.keyframes({ from: { opacity: 0 }, to: { opacity: 1 } })

/** The introduction keeps identity and purpose prominent, with optional details below. */
export const styles = stylex.create({
  actions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    gridColumn: "1 / -1",
    justifyContent: "flex-end",
  },
  cancel: {
    borderRadius: 8,
    color: theme["--muted"],
    cursor: "pointer",
    display: "grid",
    height: 40,
    placeItems: "center",
    position: "absolute",
    right: 8,
    top: 8,
    width: 40,
  },
  changeFolder: {
    backgroundColor: { ":hover": theme["--surface-muted"], default: theme["--surface-strong"] },
    borderRadius: 8,
    color: theme["--ink"],
    cursor: "pointer",
    fontSize: 13,
    minHeight: 44,
    paddingInline: 8,
  },
  character: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-muted"], default: "transparent" },
    borderColor: "transparent",
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    cursor: "pointer",
    display: "flex",
    justifyContent: "center",
    minHeight: 48,
    padding: 4,
  },
  compactIdentity: {
    alignItems: "center",
    color: theme["--muted"],
    cursor: "pointer",
    display: "flex",
    fontSize: 13,
    gap: 7,
    listStyle: "none",
    marginBottom: 8,
  },
  composerFields: { alignItems: "end", gap: 8, gridTemplateColumns: "minmax(0, 1fr) auto" },
  composerInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxShadow: "none",
    fontSize: { "@media (max-width: 720px)": 16, default: 15 },
    gridColumn: "1 / -1",
    lineHeight: 1.5,
    maxHeight: "min(320px, 40dvh)",
    minHeight: 88,
    overflowY: "auto",
    padding: "8px 24px 8px 0",
    resize: "none",
  },
  composerSubmit: { gridColumn: 2, paddingInline: 20, width: "auto" },
  controls: {
    marginInline: "auto",
    maxWidth: 720,
    minWidth: 0,
    pointerEvents: "auto",
    width: "100%",
  },
  creationComposer: { maxWidth: 720, position: "relative", textAlign: "left", width: "100%" },
  creationStage: {
    alignItems: "flex-end",
    display: "flex",
    flex: 1,
    justifyContent: "center",
    minHeight: 0,
    overflowY: "auto",
    padding: "24px 20px 40px",
  },
  customize: { gridColumn: 1, minWidth: 0 },
  customizeExpanded: { gridColumn: "1 / -1" },
  description: { fontSize: 14, lineHeight: 1.5, marginBottom: 16, textWrap: "pretty" },
  details: { color: theme["--muted"], fontSize: 13 },
  dialog: {
    borderRadius: 22,
    gap: 8,
    maxHeight: "calc(100dvh - 32px)",
    maxWidth: "min(520px, calc(100vw - 32px))",
    overflowY: "auto",
    padding: { "@media (max-width: 480px)": 20, default: 28 },
  },
  draftFooter: { alignItems: "center", display: "flex", flexWrap: "wrap", gap: 8, minWidth: 0 },
  draftIdentity: { alignItems: "center", flexDirection: "row", gap: 10, paddingInlineEnd: 0 },
  error: { color: theme["--danger"], fontSize: 13, lineHeight: 1.5 },
  fields: {
    borderWidth: 0,
    display: "grid",
    gap: 20,
    gridTemplateColumns: "minmax(0, 1fr)",
    margin: 0,
    minWidth: 0,
    padding: 0,
  },
  folder: { display: "grid", flex: 1, gap: 3, minWidth: 0 },
  folderName: { color: theme["--ink"], fontWeight: 500, lineHeight: 1.5, overflowWrap: "anywhere" },
  fullWidth: { gridColumn: "1 / -1", minWidth: 0 },
  gallery: {
    display: "grid",
    gap: 8,
    gridTemplateColumns: "repeat(auto-fit, minmax(44px, 1fr))",
    maxWidth: 352,
    minWidth: 0,
    width: "100%",
  },
  galleryHeading: {
    alignItems: "center",
    color: theme["--muted"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: 13,
    fontWeight: 500,
    gap: 10,
    justifyContent: "space-between",
    lineHeight: 1.5,
    marginBottom: 6,
    minWidth: 0,
  },
  icon: { flexShrink: 0, height: 15, width: 15 },
  identity: { alignItems: "center", display: "flex", gap: 16, minWidth: 0, paddingInlineEnd: 28 },
  inlinePanel: {
    backgroundColor: theme["--surface-muted"],
    borderRadius: 16,
    color: theme["--ink"],
    padding: 20,
    position: "relative",
    width: "100%",
  },
  inspection: { height: "min(440px, 50dvh)", overflow: "auto" },
  keyboard: {
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
  },
  label: {
    color: theme["--ink"],
    display: "grid",
    fontSize: 13,
    fontWeight: 500,
    gap: 8,
    lineHeight: 1.5,
  },
  name: {
    backgroundColor: "transparent",
    borderBottomColor: theme["--rule-strong"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderRadius: 0,
    borderWidth: 0,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    color: theme["--ink"],
    fontSize: 16,
    fontWeight: 500,
    height: 44,
    lineHeight: 1.5,
    minWidth: 0,
    paddingInline: 0,
    width: "100%",
  },
  nameLabel: {
    color: theme["--muted"],
    display: "grid",
    flex: 1,
    fontSize: 13,
    fontWeight: 500,
    gap: 6,
    lineHeight: 1.5,
    minWidth: 0,
    textWrap: "pretty",
  },
  nameRandomizer: {
    backgroundColor: { ":hover": theme["--surface-muted"], default: "transparent" },
    borderRadius: 8,
    color: theme["--muted"],
    cursor: "pointer",
    display: "grid",
    flexShrink: 0,
    height: 40,
    placeItems: "center",
    width: 40,
  },
  nameRow: { alignItems: "center", display: "flex", gap: 4, minWidth: 0 },
  nameUndo: {
    backgroundColor: "transparent",
    color: theme["--muted"],
    cursor: "pointer",
    fontSize: 12,
    justifySelf: "start",
    minHeight: 24,
    padding: 0,
    textDecorationLine: "underline",
  },
  notes: {
    fontSize: { "@media (max-width: 720px)": 16, default: 14 },
    lineHeight: 1.5,
    marginTop: 0,
    maxHeight: 320,
    minHeight: 104,
    overflowY: "auto",
    resize: "none",
  },
  portrait: {
    "@media (max-width: 480px)": { height: 40, width: 40 },
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "50%",
    display: "inline-flex",
    flexShrink: 0,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  purpose: {
    borderRadius: 12,
    fontSize: 14,
    lineHeight: 1.5,
    minHeight: 78,
    padding: "12px 14px",
    resize: "none",
  },
  reveal: {
    height: {
      ":is([data-starting-style], [data-ending-style])": 0,
      default: "var(--collapsible-panel-height)",
    },
    opacity: { ":is([data-starting-style], [data-ending-style])": 0, default: 1 },
    overflow: "hidden",
    transitionDuration: {
      "@media (prefers-reduced-motion: no-preference)": "220ms",
      default: "0ms",
    },
    transitionProperty: "height, opacity",
    transitionTimingFunction: "ease-out",
  },
  revealContent: {
    animationDuration: { "@media (prefers-reduced-motion: reduce)": "80ms", default: "160ms" },
    animationName: { "@media (prefers-reduced-motion: reduce)": tabFade, default: tabEnter },
    animationTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)",
    paddingBlock: 8,
  },
  save: {
    backgroundColor: { ":hover": theme["--surface-strong"], default: theme["--surface"] },
    borderRadius: 10,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    color: theme["--ink"],
    height: "auto",
    minHeight: 40,
    padding: "10px 18px",
    whiteSpace: "normal",
  },
  saveStatus: {
    color: theme["--muted"],
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
    marginInlineEnd: "auto",
  },
  selected: {
    backgroundColor: theme["--surface-strong"],
    borderColor: { "@media (forced-colors: active)": "Highlight", default: theme["--muted"] },
  },
  settingsReveal: {
    opacity: { ":is([data-starting-style], [data-ending-style])": 0, default: 1 },
    transform: {
      ":is([data-starting-style], [data-ending-style])": "translateY(-6px) scale(.985)",
      "@media (prefers-reduced-motion: reduce)": "none",
      default: "translateY(0) scale(1)",
    },
    transformOrigin: "top left",
    transitionDuration: { "@media (prefers-reduced-motion: reduce)": "80ms", default: "180ms" },
    transitionProperty: "transform, opacity",
    transitionTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)",
  },
  shuffle: {
    alignItems: "center",
    borderRadius: 7,
    color: theme["--ink"],
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 13,
    fontWeight: 500,
    gap: 6,
    lineHeight: 1.5,
    minHeight: 40,
    paddingInline: 6,
  },
  submit: {
    borderRadius: 12,
    color: theme["--on-accent"],
    fontSize: 14,
    height: "auto",
    minHeight: 44,
    paddingBlock: 12,
    whiteSpace: "normal",
    width: "100%",
  },
  summary: { cursor: "pointer", minHeight: 32, paddingBlock: 4 },
  title: {
    color: theme["--ink-strong"],
    fontFamily: '"gelica", Georgia, serif',
    fontSize: 32,
    fontWeight: 500,
    letterSpacing: "-0.035em",
    lineHeight: 1.1,
    overflowWrap: "anywhere",
    paddingRight: 20,
  },
  workspace: {
    alignItems: "start",
    borderTopColor: theme["--rule"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
    color: theme["--muted"],
    display: "grid",
    fontSize: 13,
    gap: 10,
    gridTemplateColumns: "minmax(0, 1fr)",
    paddingBlock: 12,
  },
})
