import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

const breathe = stylex.keyframes({ "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-1.5px)" } })
const blink = stylex.keyframes({ "0%, 94%, 100%": { transform: "scaleY(1)" }, "97%": { transform: "scaleY(0.15)" } })

/** Roster identity, workspace controls, and avatar variants using the shared theme. */
export const styles = stylex.create({
  icon: { width: 17, height: 17, flexShrink: 0 },
  search: { padding: "2px 16px 16px" },
  searchInput: { width: "100%", minWidth: 0, padding: "9px 11px", borderRadius: 12, borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], backgroundColor: theme["--surface"], fontSize: 13 },
  nav: { minHeight: 0, flexGrow: 1, overflowY: "auto", overflowX: "hidden", paddingBottom: 16 },
  list: { display: "grid", gap: 5, listStyleType: "none", margin: 0, padding: "0 8px" },
  item: { position: "relative", display: "flex", alignItems: "center", minWidth: 0 },
  row: { display: "flex", alignItems: "center", gap: 11, width: "100%", minWidth: 0, padding: "11px 30px 11px 9px", borderRadius: 12, textAlign: "left", backgroundColor: { default: "transparent", ":hover": theme["--surface-strong"] } },
  selected: { backgroundColor: theme["--surface-strong"], borderWidth: { default: null, "@media (forced-colors: active)": 1 }, borderStyle: { default: null, "@media (forced-colors: active)": "solid" }, borderColor: { default: null, "@media (forced-colors: active)": "Highlight" } },
  rowText: { display: "grid", minWidth: 0, gap: 4 },
  name: { display: "block", fontSize: 14, fontWeight: 570, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  preview: { color: theme["--muted"], fontSize: 12, lineHeight: 1.45, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  avatar: { display: "inline-flex", flexShrink: 0, flexBasis: 42, width: 42, height: 42 },
  avatarLarge: { width: 70, height: 70, flexBasis: 70 },
  avatarSmall: { width: 28, height: 28, flexBasis: 28 },
  avatarSvg: { width: "100%", height: "100%" },
  working: { animationName: { default: breathe, "@media (prefers-reduced-motion: reduce)": "none" }, animationDuration: "2.5s", animationTimingFunction: "ease-in-out", animationIterationCount: "infinite" },
  workingEyes: { transformOrigin: "center", animationName: { default: blink, "@media (prefers-reduced-motion: reduce)": "none" }, animationDuration: "4s", animationIterationCount: "infinite" },
  favorite: { position: "absolute", right: 4, padding: 7, borderRadius: 6, color: { default: theme["--faint"], ":hover": theme["--ink"] } },
  favorited: { color: theme["--accent"] },
  favoriteIcon: { width: 14, height: 14 },
  favoriteIconFilled: { fill: "currentColor" },
  empty: { padding: "24px 17px", color: theme["--muted"], fontSize: 13, lineHeight: 1.6 },
  emptyAction: { marginTop: 12 },
  history: { display: "flex", alignItems: "center", gap: 9, width: "calc(100% - 24px)", margin: "24px 12px 8px", padding: 10, borderRadius: 8, color: theme["--muted"], fontSize: 13, textAlign: "left", backgroundColor: { default: "transparent", ":hover": theme["--surface-strong"] } },
  count: { marginLeft: "auto", fontSize: 12 },
  feedback: { margin: "10px 16px", fontSize: 12, lineHeight: 1.5, color: theme["--danger"] },
  historyList: { listStyleType: "none", margin: 0, padding: "0 12px 20px" },
  workspaceGroup: { padding: "8px 6px", fontSize: 13, color: theme["--muted"], overflowWrap: "anywhere" },
  conversationButton: { display: "block", width: "100%", padding: "9px 12px", marginTop: 3, borderRadius: 8, textAlign: "left", fontSize: 13, color: theme["--ink"], overflowWrap: "anywhere", backgroundColor: { default: "transparent", ":hover": theme["--surface-strong"] } },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: { default: 16, "@media (max-width: 640px)": 6 }, padding: { default: "15px 24px 15px 54px", "@media (max-width: 720px)": "12px 8px 12px 48px" }, flexShrink: 0, minWidth: 0, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: theme["--rule"] },
  workspacePath: { marginTop: 3, color: theme["--faint"], fontSize: 11, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  identity: { display: "flex", alignItems: "center", gap: 9, minWidth: 0 },
  identityText: { minWidth: 0 },
  role: { margin: "3px 0 0", color: theme["--muted"], fontSize: 12, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  actions: { display: "flex", gap: 3, flexShrink: 0 },
  iconButton: { display: "inline-flex", justifyContent: "center", alignItems: "center", width: 34, height: 34, borderRadius: 8, color: { default: theme["--muted"], ":hover": theme["--ink"] }, backgroundColor: { default: "transparent", ":hover": theme["--surface-strong"] } },
  menuPositioner: { zIndex: 60 },
  menu: { display: "grid", gap: 5, width: "min(320px, calc(100vw - 24px))", maxHeight: "min(460px, 75vh)", overflowY: "auto", backgroundColor: theme["--surface"], color: theme["--ink"], padding: 13, borderRadius: 12, boxShadow: "0 8px 40px #0002" },
  menuTitle: { fontSize: 14, fontWeight: 600, margin: "3px 5px 8px" },
  menuButton: { display: "flex", alignItems: "center", gap: 8, padding: 9, borderRadius: 7, textAlign: "left", fontSize: 13, overflowWrap: "anywhere", backgroundColor: { default: "transparent", ":hover": theme["--surface-strong"] } },
  menuNote: { fontSize: 12, lineHeight: 1.5, color: theme["--muted"], padding: 6 },
  settings: { maxHeight: "calc(100dvh - 32px)", overflowY: "auto" },
  fields: { display: "grid", gap: 15 },
  label: { display: "grid", gap: 6, fontSize: 13 },
  modelFields: { display: "grid", gridTemplateColumns: { default: "1fr 1fr", "@media (max-width: 640px)": "1fr" }, gap: 12 },
  hint: { fontSize: 12, lineHeight: 1.5, color: theme["--muted"] },
  choices: { display: "flex", gap: 12 },
  choice: { padding: 4, borderRadius: 12 },
  choiceSelected: { backgroundColor: theme["--surface-strong"], boxShadow: `inset 0 0 0 2px ${theme["--muted"]}` },
  welcome: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 15, width: "min(560px, 100% - 40px)", margin: "auto", padding: "32px 0" },
  welcomeTitle: { fontSize: "clamp(22px, 3vw, 30px)", fontWeight: 500, textAlign: "center", overflowWrap: "anywhere" },
  welcomeNote: { fontSize: 14, color: theme["--muted"], textAlign: "center" },
  welcomeInput: { marginTop: 16, minHeight: 100 },
  hidden: { position: "absolute", width: 1, height: 1, padding: 0, margin: -1, overflow: "hidden", clip: "rect(0, 0, 0, 0)", whiteSpace: "nowrap", borderWidth: 0 },
})
