import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"
import { shellLayout } from "../shell-layout.stylex"

const breathe = stylex.keyframes({
  "0%, 100%": { transform: "translateY(0)" },
  "50%": { transform: "translateY(-1.5px)" },
})
const idleSway = stylex.keyframes({
  "0%, 100%": { transform: "translateY(0) rotate(-3deg)" },
  "50%": { transform: "translateY(-4px) rotate(3deg)" },
})
const blink = stylex.keyframes({
  "0%, 94%, 100%": { transform: "scaleY(1)" },
  "97%": { transform: "scaleY(0.15)" },
})

/** Roster identity, workspace controls, and avatar variants using the shared theme. */
export const styles = stylex.create({
  actions: { display: "flex", flexShrink: 0, gap: 3 },
  annotationHeader: { WebkitAppRegion: "no-drag", userSelect: "text" },
  avatar: {
    backgroundColor: "transparent",
    display: "inline-flex",
    flexBasis: 42,
    flexShrink: 0,
    height: 42,
    width: 42,
  },
  avatarGroup: {
    backgroundColor: theme["--surface-strong"],
    borderRadius: "50%",
    display: "block",
    flexShrink: 0,
    height: 48,
    overflow: "hidden",
    position: "relative",
    width: 48,
  },
  avatarLarge: {
    flexBasis: { "@media (max-width: 480px)": 56, default: 88 },
    height: { "@media (max-width: 480px)": 56, default: 88 },
    width: { "@media (max-width: 480px)": 56, default: 88 },
  },
  avatarSmall: { flexBasis: 28, height: 28, width: 28 },
  avatarSvg: { height: "100%", width: "100%" },
  choice: { borderRadius: 12, padding: 4 },
  choiceSelected: {
    backgroundColor: theme["--surface-strong"],
    boxShadow: `inset 0 0 0 2px ${theme["--muted"]}`,
  },
  choices: { display: "flex", gap: 12 },
  concealed: { display: "none" },
  contextItem: {
    backgroundColor: {
      ":is([data-highlighted])": theme["--surface-muted"],
      default: "transparent",
    },
    borderRadius: 7,
    cursor: "pointer",
    fontSize: 13,
    outlineStyle: "none",
    padding: "10px 12px",
  },
  contextMenu: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 8px 30px #0002",
    minWidth: 190,
    padding: 5,
  },
  conversationButton: {
    backgroundColor: { ":hover": theme["--surface-strong"], default: "transparent" },
    borderRadius: 8,
    color: theme["--ink"],
    display: "block",
    fontSize: 13,
    marginTop: 3,
    overflowWrap: "anywhere",
    padding: "9px 12px",
    textAlign: "left",
    width: "100%",
  },
  count: { fontSize: 12, marginLeft: "auto" },
  destructiveItem: { color: theme["--danger"] },
  empty: {
    color: theme["--muted"],
    display: "grid",
    fontSize: 13,
    gap: 10,
    lineHeight: 1.55,
    padding: "28px 17px",
  },
  emptyAction: {
    alignItems: "center",
    backgroundColor: theme["--accent"],
    borderRadius: 9,
    color: theme["--on-accent"],
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 13,
    fontWeight: 650,
    justifyContent: "center",
    marginTop: 4,
    minHeight: { "@media (max-width: 720px)": 44, default: 40 },
    padding: "0 13px",
    width: "fit-content",
  },
  emptyDescription: { maxWidth: "28ch" },
  emptyTitle: {
    color: theme["--ink-strong"],
    fontSize: 16,
    fontWeight: 650,
    lineHeight: 1.35,
    overflowWrap: "anywhere",
  },
  favorite: {
    borderRadius: 6,
    color: { ":hover": theme["--ink"], default: theme["--faint"] },
    padding: 7,
    position: "absolute",
    right: 4,
  },
  favoriteIcon: { height: 14, width: 14 },
  favorited: { color: theme["--accent"] },
  feedback: { color: theme["--danger"], fontSize: 12, lineHeight: 1.5, margin: "10px 16px" },
  fields: { display: "grid", gap: 15 },
  ghostAgent: {
    aspectRatio: "1",
    filter: "grayscale(0.65)",
    opacity: 0.16,
    pointerEvents: "none",
    transform: "rotate(-8deg)",
    width: "min(160px, 100%)",
  },
  ghostCopy: {
    color: theme["--muted"],
    fontSize: 13,
    lineHeight: 1.65,
    textAlign: "center",
    textWrap: "pretty",
  },
  ghostRow: {
    alignContent: "center",
    display: "grid",
    gap: 18,
    height: "100%",
    minHeight: 220,
    padding: 24,
    placeItems: "center",
  },
  ghostTitle: {
    color: theme["--ink"],
    fontFamily: "Georgia, serif",
    fontSize: 19,
    marginBottom: 5,
  },
  groupChild: (x: number, y: number, scale: number) => ({
    display: "flex",
    height: 24,
    left: x,
    position: "absolute",
    top: y,
    transform: `translate(-50%, -50%) scale(${scale})`,
    width: 24,
  }),
  groupChildren: { inset: 0, position: "absolute" },
  groupLabel: {
    color: theme["--muted"],
    display: "block",
    fontSize: 12,
    fontWeight: 400,
    lineHeight: 1.5,
    textDecorationLine: "underline",
    textUnderlineOffset: 3,
  },
  groupParent: {
    display: "flex",
    height: 36,
    left: 6,
    position: "absolute",
    top: 0,
  },
  header: {
    WebkitAppRegion: "drag",
    alignItems: "center",
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 25,
    justifyContent: "space-between",
    minHeight: 71,
    minWidth: 0,
    paddingBlockEnd: "var(--header-bottom-padding, 4px)",
    paddingBlockStart: `calc(${shellLayout.headerTopInset} + var(--header-extra-top, 0px))`,
    paddingInlineEnd: "var(--header-end-padding, 8px)",
    paddingInlineStart: `calc(${shellLayout.headerInset} + var(--header-extra-start, 0px))`,
  },
  headerAction: { WebkitAppRegion: "no-drag", flexShrink: 0, height: 30, width: 30 },
  headerLeading: {
    WebkitAppRegion: "no-drag",
    alignItems: "center",
    display: "flex",
    flex: 1,
    flexWrap: "wrap",
    gap: 10,
    minWidth: 0,
  },
  headerUtilities: {
    WebkitAppRegion: "no-drag",
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: 2,
  },
  hidden: {
    borderWidth: 0,
    clip: "rect(0, 0, 0, 0)",
    height: 1,
    margin: -1,
    overflow: "hidden",
    padding: 0,
    position: "absolute",
    whiteSpace: "nowrap",
    width: 1,
  },
  hint: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5 },
  history: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-strong"], default: "transparent" },
    borderRadius: 8,
    color: theme["--muted"],
    display: "flex",
    fontSize: 13,
    gap: 9,
    margin: "24px 12px 8px",
    padding: 10,
    textAlign: "left",
    width: "calc(100% - 24px)",
  },
  historyEmpty: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5, padding: "12px 6px" },
  historyList: { listStyleType: "none", margin: 0, padding: "0 12px 20px" },
  icon: { flexShrink: 0, height: 17, width: 17 },
  iconButton: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-strong"], default: "transparent" },
    borderRadius: 8,
    color: { ":hover": theme["--ink"], default: theme["--muted"] },
    display: "inline-flex",
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  identity: { alignItems: "center", display: "flex", gap: 9, minWidth: 0 },
  identityText: { minWidth: 0 },
  idleMotion: {
    animationDuration: "3.2s",
    animationIterationCount: "infinite",
    animationName: { "@media (prefers-reduced-motion: reduce)": "none", default: idleSway },
    animationTimingFunction: "ease-in-out",
    transformBox: "fill-box",
    transformOrigin: "center",
  },
  item: { alignItems: "center", display: "flex", minWidth: 0, position: "relative" },
  label: { display: "grid", fontSize: 13, gap: 6 },
  list: { display: "grid", gap: 5, listStyleType: "none", margin: 0, padding: "0 8px" },
  menu: {
    backgroundColor: theme["--surface"],
    borderRadius: 12,
    boxShadow: "0 8px 40px #0002",
    color: theme["--ink"],
    display: "grid",
    gap: 5,
    maxHeight: "min(460px, 75vh)",
    overflowY: "auto",
    padding: 13,
    width: "min(320px, calc(100vw - 24px))",
  },
  menuButton: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-strong"], default: "transparent" },
    borderRadius: 7,
    display: "flex",
    fontSize: 13,
    gap: 8,
    overflowWrap: "anywhere",
    padding: 9,
    textAlign: "left",
  },
  menuButtonCopy: { display: "grid", flex: 1, gap: 2, minWidth: 0 },
  menuButtonMeta: {
    color: theme["--muted"],
    fontSize: 11,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  menuButtonStatus: {
    color: theme["--muted"],
    fontSize: 11,
    marginLeft: "auto",
    maxWidth: "14ch",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  menuButtonTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  menuNote: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5, padding: 6 },
  menuPositioner: { zIndex: 60 },
  menuTitle: { fontSize: 14, fontWeight: 600, margin: "3px 5px 8px" },
  modelFields: {
    display: "grid",
    gap: 12,
    gridTemplateColumns: { "@media (max-width: 640px)": "1fr", default: "1fr 1fr" },
  },
  name: {
    display: "block",
    fontSize: 14,
    fontWeight: 570,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  nav: { flexGrow: 1, minHeight: 0, overflowX: "hidden", overflowY: "auto", paddingBottom: 16 },
  parentRow: { pointerEvents: "none", position: "relative" },
  parentTrigger: {
    backgroundColor: "transparent",
    borderRadius: 12,
    borderWidth: 0,
    inset: 0,
    pointerEvents: "auto",
    position: "absolute",
  },
  preview: {
    color: theme["--muted"],
    fontSize: 12,
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1.45,
    overflowWrap: "anywhere",
    whiteSpace: "normal",
  },
  role: {
    color: theme["--muted"],
    fontSize: 12,
    margin: "3px 0 0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  row: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-strong"], default: "transparent" },
    borderRadius: 12,
    display: "flex",
    gap: 11,
    minWidth: 0,
    padding: "6px 30px 6px 9px",
    textAlign: "left",
    width: "100%",
  },
  rowText: { display: "grid", gap: 4, minWidth: 0 },
  search: { padding: "2px 16px 16px" },
  searchInput: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    fontSize: { "@media (max-width: 720px)": 16, default: 13 },
    minWidth: 0,
    padding: "9px 11px",
    width: "100%",
  },
  selected: {
    backgroundColor: theme["--surface-strong"],
    borderColor: { "@media (forced-colors: active)": "Highlight", default: null },
    borderStyle: { "@media (forced-colors: active)": "solid", default: null },
    borderWidth: { "@media (forced-colors: active)": 1, default: null },
  },
  settings: { maxHeight: "calc(100dvh - 32px)", overflowY: "auto" },
  settingsHost: { flex: 1, minHeight: 0, overflowY: "auto", padding: "0 16px 20px" },
  welcomeInput: { marginTop: 16, minHeight: 100 },
  working: {
    animationDuration: "2.5s",
    animationIterationCount: "infinite",
    animationName: { "@media (prefers-reduced-motion: reduce)": "none", default: breathe },
    animationTimingFunction: "ease-in-out",
  },
  workingEyes: {
    animationDuration: "4s",
    animationIterationCount: "infinite",
    animationName: { "@media (prefers-reduced-motion: reduce)": "none", default: blink },
    transformOrigin: "center",
  },
  workspaceGroup: {
    color: theme["--muted"],
    fontSize: 13,
    overflowWrap: "anywhere",
    padding: "8px 6px",
  },
  workspacePath: {
    color: theme["--faint"],
    fontSize: 11,
    marginTop: 3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
})
