import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

const tabEnter = stylex.keyframes({ from: { opacity: 0, transform: "translateX(6px)" }, to: { opacity: 1, transform: "translateX(0)" } })
const tabFade = stylex.keyframes({ from: { opacity: 0 }, to: { opacity: 1 } })

/** The introduction keeps identity and purpose prominent, with optional details below. */
export const styles = stylex.create({
  reveal: { height: { default: "var(--collapsible-panel-height)", ":is([data-starting-style], [data-ending-style])": 0 }, opacity: { default: 1, ":is([data-starting-style], [data-ending-style])": 0 }, overflow: "hidden", transitionProperty: "height, opacity", transitionDuration: { default: "0ms", "@media (prefers-reduced-motion: no-preference)": "220ms" }, transitionTimingFunction: "ease-out" },
  settingsReveal: {
    opacity: { default: 1, ":is([data-starting-style], [data-ending-style])": 0 },
    transform: { default: "translateY(0) scale(1)", ":is([data-starting-style], [data-ending-style])": "translateY(-6px) scale(.985)", "@media (prefers-reduced-motion: reduce)": "none" },
    transformOrigin: "top left",
    transitionProperty: "transform, opacity",
    transitionDuration: { default: "180ms", "@media (prefers-reduced-motion: reduce)": "80ms" },
    transitionTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)",
  },
  revealContent: { paddingBlock: 8, animationName: { default: tabEnter, "@media (prefers-reduced-motion: reduce)": tabFade }, animationDuration: { default: "160ms", "@media (prefers-reduced-motion: reduce)": "80ms" }, animationTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)" },
  inspection: { height: "min(440px, 50dvh)", overflow: "auto" },
  controls: { pointerEvents: "auto", width: "100%", maxWidth: 720, marginInline: "auto", minWidth: 0 },
  fullWidth: { minWidth: 0, gridColumn: "1 / -1" },
  inlinePanel: { position: "relative", padding: 20, borderRadius: 16, backgroundColor: theme["--surface-muted"], color: theme["--ink"], width: "100%" },
  creationStage: { display: "flex", flex: 1, minHeight: 0, alignItems: "flex-end", justifyContent: "center", padding: "24px 20px 40px", overflowY: "auto" },
  draftIdentity: { flexDirection: "row", alignItems: "center", gap: 10, paddingInlineEnd: 0 },
  creationComposer: { position: "relative", width: "100%", maxWidth: 720, textAlign: "left" },
  composerFields: { gridTemplateColumns: "minmax(0, 1fr) auto", gap: 8, alignItems: "end" },
  composerSubmit: { width: "auto", paddingInline: 20, gridColumn: 2 },
  composerInput: { borderWidth: 0, backgroundColor: "transparent", boxShadow: "none", resize: "none", padding: "8px 24px 8px 0", minHeight: 88, maxHeight: "min(320px, 40dvh)", overflowY: "auto", fontSize: { default: 15, "@media (max-width: 720px)": 16 }, lineHeight: 1.5, gridColumn: "1 / -1" },
  customize: { minWidth: 0, gridColumn: 1 },
  customizeExpanded: { gridColumn: "1 / -1" },
  compactIdentity: { display: "flex", alignItems: "center", gap: 7, cursor: "pointer", fontSize: 13, color: theme["--muted"], marginBottom: 8, listStyle: "none" },
  cancel: { position: "absolute", right: 8, top: 8, display: "grid", placeItems: "center", width: 40, height: 40, color: theme["--muted"], cursor: "pointer", borderRadius: 8 },
  dialog: { maxWidth: "min(520px, calc(100vw - 32px))", maxHeight: "calc(100dvh - 32px)", overflowY: "auto", padding: { default: 28, "@media (max-width: 480px)": 20 }, borderRadius: 22, gap: 8 },
  title: { fontFamily: '"gelica", Georgia, serif', fontSize: 32, lineHeight: 1.1, fontWeight: 500, letterSpacing: "-0.035em", paddingRight: 20, color: theme["--ink-strong"], overflowWrap: "anywhere" },
  description: { textWrap: "pretty", lineHeight: 1.5, fontSize: 14, marginBottom: 16 },
  fields: { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: 20, borderWidth: 0, padding: 0, margin: 0, minWidth: 0 },
  identity: { display: "flex", alignItems: "center", gap: 16, paddingInlineEnd: 28, minWidth: 0 },
  portrait: { display: "inline-flex", alignItems: "center", justifyContent: "center", width: 40, height: 40, flexShrink: 0, borderRadius: "50%", backgroundColor: "transparent", "@media (max-width: 480px)": { width: 40, height: 40 } },
  nameUndo: { justifySelf: "start", minHeight: 24, padding: 0, fontSize: 12, color: theme["--muted"], backgroundColor: "transparent", cursor: "pointer", textDecoration: "underline" },
  nameRow: { display: "flex", alignItems: "center", minWidth: 0, gap: 4 },
  nameRandomizer: { display: "grid", placeItems: "center", width: 40, height: 40, flexShrink: 0, borderRadius: 8, color: theme["--muted"], backgroundColor: { default: "transparent", ":hover": theme["--surface-muted"] }, cursor: "pointer" },
  nameLabel: { display: "grid", gap: 6, minWidth: 0, flex: 1, color: theme["--muted"], fontSize: 13, fontWeight: 500, lineHeight: 1.5, textWrap: "pretty" },
  name: { minWidth: 0, width: "100%", outlineWidth: { default: 0, ":focus-visible": 2 }, outlineStyle: "solid", outlineOffset: 2, outlineColor: { default: theme["--ink"], "@media (forced-colors: active)": "Highlight" }, height: 44, paddingInline: 0, fontSize: 16, lineHeight: 1.5, color: theme["--ink"], fontWeight: 500, backgroundColor: "transparent", borderWidth: 0, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: theme["--rule-strong"], borderRadius: 0, boxShadow: "none" },
  gallery: { minWidth: 0, width: "100%", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(44px, 1fr))", maxWidth: 352, gap: 8 },
  character: { display: "flex", alignItems: "center", justifyContent: "center", minHeight: 48, padding: 4, borderRadius: 10, borderWidth: 1, borderStyle: "solid", borderColor: "transparent", backgroundColor: { default: "transparent", ":hover": theme["--surface-muted"] }, cursor: "pointer" },
  selected: { backgroundColor: theme["--surface-strong"], borderColor: { default: theme["--muted"], "@media (forced-colors: active)": "Highlight" } },
  galleryHeading: { minWidth: 0, flexWrap: "wrap", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 6, fontSize: 13, fontWeight: 500, lineHeight: 1.5, color: theme["--muted"] },
  keyboard: { outlineWidth: { default: 0, ":focus-visible": 2 }, outlineStyle: "solid", outlineOffset: 2, outlineColor: { default: theme["--ink"], "@media (forced-colors: active)": "Highlight" } },
  actions: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 12, justifyContent: "flex-end", gridColumn: "1 / -1" },
  saveStatus: { margin: 0, marginInlineEnd: "auto", fontSize: 13, lineHeight: 1.5, color: theme["--muted"] },
  save: { outlineWidth: { default: 0, ":focus-visible": 2 }, outlineStyle: "solid", outlineOffset: 2, outlineColor: { default: theme["--ink"], "@media (forced-colors: active)": "Highlight" }, minHeight: 40, height: "auto", padding: "10px 18px", borderRadius: 10, color: theme["--ink"], backgroundColor: { default: theme["--surface"], ":hover": theme["--surface-strong"] }, whiteSpace: "normal" },
  shuffle: { display: "inline-flex", alignItems: "center", gap: 6, minHeight: 40, paddingInline: 6, borderRadius: 7, fontSize: 13, fontWeight: 500, lineHeight: 1.5, color: theme["--ink"], cursor: "pointer" },
  icon: { width: 15, height: 15, flexShrink: 0 },
  label: { display: "grid", gap: 8, fontSize: 13, fontWeight: 500, lineHeight: 1.5, color: theme["--ink"] },
  purpose: { minHeight: 78, padding: "12px 14px", resize: "none", fontSize: 14, lineHeight: 1.5, borderRadius: 12 },
  details: { color: theme["--muted"], fontSize: 13 },
  summary: { cursor: "pointer", paddingBlock: 4, minHeight: 32 },
  notes: { resize: "none", maxHeight: 320, overflowY: "auto", marginTop: 0, minHeight: 104, fontSize: { default: 14, "@media (max-width: 720px)": 16 }, lineHeight: 1.5 },
  draftFooter: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, minWidth: 0 },
  workspace: { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", alignItems: "start", gap: 10, paddingBlock: 12, borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: theme["--rule"], fontSize: 13, color: theme["--muted"] },
  folder: { flex: 1, minWidth: 0, display: "grid", gap: 3 },
  folderName: { color: theme["--ink"], overflowWrap: "anywhere", fontWeight: 500, lineHeight: 1.5 },
  changeFolder: { minHeight: 44, borderRadius: 8, paddingInline: 8, fontSize: 13, color: theme["--ink"], cursor: "pointer", backgroundColor: { default: theme["--surface-strong"], ":hover": theme["--surface-muted"] } },
  submit: { color: theme["--on-accent"], minHeight: 44, borderRadius: 12, width: "100%", height: "auto", paddingBlock: 12, fontSize: 14, whiteSpace: "normal" },
  error: { color: theme["--danger"], fontSize: 13, lineHeight: 1.5 },
})
