import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

export const styles = stylex.create({
  accordionDetail: { padding: 20, backgroundColor: theme["--surface"], borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: theme["--rule"] },
  technicalDetails: { marginBlock: 16 },
  technicalSummary: {
    cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "space-between",
    gap: 12, minHeight: 40, padding: "10px 12px", fontSize: 13, fontWeight: 500,
    borderRadius: 8, borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"],
    backgroundColor: { default: theme["--surface"], ":hover": theme["--surface-muted"] },
    listStyle: "none",
    "::-webkit-details-marker": { display: "none" },
    outline: { default: null, ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: 2,
  },
  technicalChevron: {
    flexShrink: 0, color: theme["--muted"],
    transform: { default: "rotate(0deg)", ":is(details[open] > summary > svg)": "rotate(180deg)" },
    transition: "transform 180ms ease-out",
    "@media (prefers-reduced-motion: reduce)": { transition: "none" },
  },
  fileRow: { width: "100%", borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], marginBlock: 8, gap: 8 },
  fileChange: { fontSize: 11, color: theme["--muted"], flexShrink: 0 },
  filePath: { fontFamily: "var(--font-mono, monospace)", fontSize: 12, overflowWrap: "anywhere", minWidth: 0, flexGrow: 1 },

  historyToolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 12, flexWrap: "wrap" },
  historyToolbarActions: { display: "flex", alignItems: "center", gap: 6 },
  historyMenu: { position: "relative" },
  historyMenuPanel: { position: "absolute", insetInlineEnd: 0, top: "100%", zIndex: 5, minWidth: 190, padding: 6, backgroundColor: theme["--surface"], borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], borderRadius: 10, boxShadow: "0 4px 16px rgb(0 0 0 / .12)" },
  screenshotStack: { position: "relative", width: 42, height: 30, display: "block", color: theme["--faint"] },
  screenshotBack: { position: "absolute", inset: "0 3px 4px 0", borderRadius: 4, borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], backgroundColor: theme["--surface-muted"], transform: "rotate(-8deg)" },
  screenshotFront: { position: "absolute", inset: "3px 0 0 3px", borderRadius: 4, borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], backgroundColor: theme["--surface"], display: "flex", alignItems: "center", justifyContent: "center" },
  historyStatus: { fontSize: 12, fontWeight: 400, marginBlock: "8px 24px", color: theme["--ink"] },
  historyPrimary: { borderRadius: 9, backdropFilter: "blur(10px)", backgroundColor: { default: "#fff", ":hover": "#f5f5f5" }, color: "#171717", borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], fontSize: 12, fontWeight: 500, opacity: { default: 1, ":disabled": 0.6 } },
  checkpointList: { borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], borderRadius: 12, overflow: "hidden" },
  checkpointRow: { width: "100%", display: "grid", gridTemplateColumns: { default: "minmax(0, 1fr) 48px 100px 16px", "@container (max-width: 420px)": "minmax(0, 1fr) 48px 16px" }, gap: 12, padding: "8px 16px", borderRadius: 0, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: theme["--rule"] },
  checkpointText: { minWidth: 0, display: "flex", flexDirection: "column", gap: 4 },
  checkpointTitle: { fontSize: 12, fontWeight: 500, overflowWrap: "anywhere" },
  checkpointMeta: { fontSize: 8, lineHeight: 1.5, color: theme["--muted"] },
  checkpointBadge: { fontSize: 12, whiteSpace: "nowrap", color: theme["--muted"], textAlign: "end", gridColumn: { default: "auto", "@container (max-width: 420px)": "1 / -1" }, gridRow: { default: "auto", "@container (max-width: 420px)": 2 } },
  currentCheckpoint: { backgroundColor: { default: theme["--surface-muted"], ":hover": theme["--surface-strong"] } },
  selectedCheckpoint: { backgroundColor: { default: theme["--focus-soft"], ":hover": theme["--focus-soft"] } },
  previewNotice: { fontSize: 12, color: theme["--muted"], padding: "10px 12px", borderRadius: 8, backgroundColor: theme["--surface-muted"], marginBottom: 16 },
  appearanceRows: { borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], borderRadius: 12, overflow: "hidden", marginTop: 16 },
  appearanceRow: { display: "grid", gridTemplateColumns: { default: "minmax(0, 1fr) minmax(140px, 44%)", "@container (max-width: 360px)": "minmax(0, 1fr)" }, alignItems: "center", gap: "8px 16px", padding: "16px", borderBottomWidth: { default: 1, ":last-child": 0 }, borderBottomStyle: "solid", borderBottomColor: theme["--rule"] },
  appearanceLabel: { fontSize: 14, fontWeight: 500, margin: 0 },
  appearanceHint: { fontSize: 12, lineHeight: 1.5, color: theme["--muted"], marginBlock: "4px 0" },
  fontPreview: { gridColumn: "1 / -1", fontSize: 12, padding: 12, borderRadius: 6, backgroundColor: theme["--surface-muted"], margin: 0, overflowWrap: "anywhere", whiteSpace: "pre-wrap", color: theme["--muted"] },
  monoPreview: { fontFamily: "var(--font-mono, monospace)" },
  appearanceSelect: { width: "100%", minWidth: 0, minHeight: 40 },
  appearance: { marginBottom: 24 },
  page: { height: "100%", minHeight: 0, overflowY: "auto", padding: "24px clamp(18px, 4vw, 48px)", color: theme["--ink"] },
  content: { containerType: "inline-size", maxWidth: 760, marginInline: "auto" },
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 24 },
  title: { fontSize: 24, fontWeight: 600, margin: 0 },
  trigger: { minHeight: 44, padding: "10px 16px", display: "flex", alignItems: "center", gap: 8, cursor: "pointer", color: theme["--muted"] },
  button: { minHeight: 44, cursor: "pointer", borderRadius: 10, padding: "10px 12px", display: "flex", alignItems: "center", gap: 10, textAlign: "left", backgroundColor: { default: "transparent", ":hover": theme["--surface-muted"] }, color: theme["--ink"] },
  row: { width: "100%", justifyContent: "space-between", padding: "18px 12px", borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: theme["--rule"] },
  description: { fontSize: 13, lineHeight: 1.5, color: theme["--muted"], marginBlock: 12 },
  actions: { display: "flex", gap: 8, flexWrap: "wrap", marginBlock: 16 },
  list: { padding: 0, listStyle: "none", margin: 0 },
  detailHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
  detailTitle: { fontSize: 16, fontWeight: 500, color: theme["--muted"] },
  completeBadge: { backgroundColor: theme["--success-soft"], color: theme["--success"] },
  detailBadge: { fontSize: 11, padding: "4px 8px", borderRadius: 999, backgroundColor: theme["--surface-muted"], color: theme["--muted"] },
  detailMetric: { display: "flex", alignItems: "center", gap: 14, marginBlock: "8px 20px" },
  detailCount: { fontSize: 42, fontWeight: 500, letterSpacing: "-0.04em", lineHeight: 1.1 },
  detailFacts: { display: "grid", gap: 12, paddingBlock: 20, marginBottom: 16, borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: theme["--rule"] },
  detailFact: { display: "flex", flexWrap: "wrap", justifyContent: "space-between", gap: "4px 16px", fontSize: 12, color: theme["--muted"] },
  detail: { marginBlock: 24, padding: "clamp(20px, 4vw, 28px)", borderRadius: 24, backgroundColor: theme["--surface"], borderWidth: 1, borderStyle: "solid", borderColor: theme["--rule"], boxShadow: "0 2px 3px rgb(0 0 0 / .06), 0 12px 24px -20px rgb(0 0 0 / .25)" },
  pre: { whiteSpace: "pre-wrap", overflowWrap: "anywhere", maxHeight: 320, overflow: "auto", fontSize: 12, padding: 12, backgroundColor: theme["--surface"] },
  historyRow: { width: "100%", gap: 16, marginTop: 24, padding: "18px 12px" },
  historyText: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 6 },
  historyDescription: { fontSize: 13, lineHeight: 1.5, color: theme["--muted"] },
  tabs: { display: "flex", gap: 8, marginBottom: 24, borderBottom: "1px solid", borderColor: theme["--rule"], paddingBottom: 8 },
  selectedTab: { backgroundColor: theme["--surface-muted"], fontWeight: 600 },
  scopeTitle: { margin: 0, fontSize: 16, fontWeight: 600 },
  hidden: { display: "none" },
})
