import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

export const styles = stylex.create({
  accordionDetail: {
    backgroundColor: theme["--surface"],
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    padding: 20,
  },
  actions: { display: "flex", flexWrap: "wrap", gap: 8, marginBlock: 16 },
  appearance: { marginBottom: 24 },
  appearanceHint: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5, marginBlock: "4px 0" },
  appearanceLabel: { fontSize: 14, fontWeight: 500, margin: 0 },
  appearanceRow: {
    alignItems: "center",
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: { ":last-child": 0, default: 1 },
    display: "grid",
    gap: "8px 16px",
    gridTemplateColumns: {
      "@container (max-width: 360px)": "minmax(0, 1fr)",
      default: "minmax(0, 1fr) minmax(140px, 44%)",
    },
    padding: "16px",
  },
  appearanceRows: {
    borderColor: theme["--rule"],
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    marginTop: 16,
    overflow: "hidden",
  },
  appearanceSelect: { minHeight: 40, minWidth: 0, width: "100%" },
  button: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-muted"], default: "transparent" },
    borderRadius: 10,
    color: theme["--ink"],
    cursor: "pointer",
    display: "flex",
    gap: 10,
    minHeight: 44,
    padding: "10px 12px",
    textAlign: "left",
  },
  checkpointBadge: {
    color: theme["--muted"],
    fontSize: 12,
    gridColumn: { "@container (max-width: 420px)": "1 / -1", default: "auto" },
    gridRow: { "@container (max-width: 420px)": 2, default: "auto" },
    textAlign: "end",
    whiteSpace: "nowrap",
  },
  checkpointList: {
    borderColor: theme["--rule"],
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  checkpointMeta: { color: theme["--muted"], fontSize: 8, lineHeight: 1.5 },
  checkpointRow: {
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderRadius: 0,
    display: "grid",
    gap: 12,
    gridTemplateColumns: {
      "@container (max-width: 420px)": "minmax(0, 1fr) 48px 16px",
      default: "minmax(0, 1fr) 48px 100px 16px",
    },
    padding: "8px 16px",
    width: "100%",
  },
  checkpointText: { display: "flex", flexDirection: "column", gap: 4, minWidth: 0 },
  checkpointTitle: { fontSize: 12, fontWeight: 500, overflowWrap: "anywhere" },
  completeBadge: { backgroundColor: theme["--success-soft"], color: theme["--success"] },
  content: { containerType: "inline-size", marginInline: "auto", maxWidth: 760 },
  currentCheckpoint: {
    backgroundColor: { ":hover": theme["--surface-strong"], default: theme["--surface-muted"] },
  },
  description: { color: theme["--muted"], fontSize: 13, lineHeight: 1.5, marginBlock: 12 },
  detail: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 24,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 2px 3px rgb(0 0 0 / .06), 0 12px 24px -20px rgb(0 0 0 / .25)",
    marginBlock: 24,
    padding: "clamp(20px, 4vw, 28px)",
  },
  detailBadge: {
    backgroundColor: theme["--surface-muted"],
    borderRadius: 999,
    color: theme["--muted"],
    fontSize: 11,
    padding: "4px 8px",
  },
  detailCount: { fontSize: 42, fontWeight: 500, letterSpacing: "-0.04em", lineHeight: 1.1 },
  detailFact: {
    color: theme["--muted"],
    display: "flex",
    flexWrap: "wrap",
    fontSize: 12,
    gap: "4px 16px",
    justifyContent: "space-between",
  },
  detailFacts: {
    borderTopColor: theme["--rule"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
    display: "grid",
    gap: 12,
    marginBottom: 16,
    paddingBlock: 20,
  },
  detailHeader: { alignItems: "center", display: "flex", gap: 12, justifyContent: "space-between" },
  detailMetric: { alignItems: "center", display: "flex", gap: 14, marginBlock: "8px 20px" },
  detailTitle: { color: theme["--muted"], fontSize: 16, fontWeight: 500 },
  fileChange: { color: theme["--muted"], flexShrink: 0, fontSize: 11 },
  filePath: {
    flexGrow: 1,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    minWidth: 0,
    overflowWrap: "anywhere",
  },
  fileRow: {
    borderColor: theme["--rule"],
    borderStyle: "solid",
    borderWidth: 1,
    gap: 8,
    marginBlock: 8,
    width: "100%",
  },
  fontPreview: {
    backgroundColor: theme["--surface-muted"],
    borderRadius: 6,
    color: theme["--muted"],
    fontSize: 12,
    gridColumn: "1 / -1",
    margin: 0,
    overflowWrap: "anywhere",
    padding: 12,
    whiteSpace: "pre-wrap",
  },
  header: { alignItems: "center", display: "flex", gap: 12, marginBottom: 24 },
  hidden: { display: "none" },
  historyDescription: { color: theme["--muted"], fontSize: 13, lineHeight: 1.5 },
  historyMenu: { position: "relative" },
  historyMenuPanel: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: "0 4px 16px rgb(0 0 0 / .12)",
    insetInlineEnd: 0,
    minWidth: 190,
    padding: 6,
    position: "absolute",
    top: "100%",
    zIndex: 5,
  },
  historyPrimary: {
    backdropFilter: "blur(10px)",
    backgroundColor: { ":hover": "#f5f5f5", default: "#fff" },
    borderColor: theme["--rule"],
    borderRadius: 9,
    borderStyle: "solid",
    borderWidth: 1,
    color: "#171717",
    fontSize: 12,
    fontWeight: 500,
    opacity: { ":disabled": 0.6, default: 1 },
  },
  historyRow: { gap: 16, marginTop: 24, padding: "18px 12px", width: "100%" },
  historyStatus: { color: theme["--ink"], fontSize: 12, fontWeight: 400, marginBlock: "8px 24px" },
  historyText: { display: "flex", flex: 1, flexDirection: "column", gap: 6, minWidth: 0 },
  historyToolbar: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    justifyContent: "space-between",
    marginBottom: 12,
  },
  historyToolbarActions: { alignItems: "center", display: "flex", gap: 6 },
  list: { listStyle: "none", margin: 0, padding: 0 },
  monoPreview: { fontFamily: "var(--font-mono, monospace)" },
  page: {
    color: theme["--ink"],
    height: "100%",
    minHeight: 0,
    overflowY: "auto",
    padding: "24px clamp(18px, 4vw, 48px)",
  },
  pre: {
    backgroundColor: theme["--surface"],
    fontSize: 12,
    maxHeight: 320,
    overflow: "auto",
    overflowWrap: "anywhere",
    padding: 12,
    whiteSpace: "pre-wrap",
  },
  previewNotice: {
    backgroundColor: theme["--surface-muted"],
    borderRadius: 8,
    color: theme["--muted"],
    fontSize: 12,
    marginBottom: 16,
    padding: "10px 12px",
  },
  row: {
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    justifyContent: "space-between",
    padding: "18px 12px",
    width: "100%",
  },
  scopeTitle: { fontSize: 16, fontWeight: 600, margin: 0 },
  screenshotBack: {
    backgroundColor: theme["--surface-muted"],
    borderColor: theme["--rule"],
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    inset: "0 3px 4px 0",
    position: "absolute",
    transform: "rotate(-8deg)",
  },
  screenshotFront: {
    alignItems: "center",
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 4,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    inset: "3px 0 0 3px",
    justifyContent: "center",
    position: "absolute",
  },
  screenshotStack: {
    color: theme["--faint"],
    display: "block",
    height: 30,
    position: "relative",
    width: 42,
  },
  selectedCheckpoint: {
    backgroundColor: { ":hover": theme["--focus-soft"], default: theme["--focus-soft"] },
  },
  selectedTab: { backgroundColor: theme["--surface-muted"], fontWeight: 600 },
  tabs: {
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    borderColor: theme["--rule"],
    display: "flex",
    gap: 8,
    marginBottom: 24,
    paddingBottom: 8,
  },
  technicalChevron: {
    "@media (prefers-reduced-motion: reduce)": { transition: "none" },
    color: theme["--muted"],
    flexShrink: 0,
    transform: { ":is(details[open] > summary > svg)": "rotate(180deg)", default: "rotate(0deg)" },
    transition: "transform 180ms ease-out",
  },
  technicalDetails: { marginBlock: 16 },
  technicalSummary: {
    "::-webkit-details-marker": { display: "none" },
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-muted"], default: theme["--surface"] },
    borderColor: theme["--rule"],
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    cursor: "pointer",
    display: "flex",
    fontSize: 13,
    fontWeight: 500,
    gap: 12,
    justifyContent: "space-between",
    listStyle: "none",
    minHeight: 40,
    padding: "10px 12px",
  },
  title: { fontSize: 24, fontWeight: 600, margin: 0 },
  trigger: {
    alignItems: "center",
    color: theme["--muted"],
    cursor: "pointer",
    display: "flex",
    gap: 8,
    minHeight: 44,
    padding: "10px 16px",
  },
})
