import * as stylex from "@stylexjs/stylex"
import { shellLayout } from "../shell-layout.stylex"
import { theme } from "../theme.stylex"

/** The conversation is clear of native controls when the browser occupies the leading edge. */
export const browserConversationLayout = stylex.createTheme(shellLayout, {
  headerInset: "20px",
  headerTopInset: "0px",
})

/** Browser chrome uses the workspace palette and adapts to the space beside the conversation. */
export const styles = stylex.create({
  address: {
    backgroundColor: "transparent",
    borderColor: {
      "@media (forced-colors: active)": { ":focus-visible": "Highlight", default: "transparent" },
      default: "transparent",
    },
    borderStyle: "solid",
    borderWidth: { "@media (forced-colors: active)": 2, default: 0 },
    boxShadow: { ":focus-visible": `inset 0 0 0 2px ${theme["--focus"]}`, default: "none" },
    color: theme["--ink"],
    flex: 1,
    fontFamily: "inherit",
    fontSize: 13,
    minHeight: 30,
    minWidth: 0,
    outlineStyle: "none",
    paddingInline: 6,
  },
  addressField: {
    alignItems: "center",
    backgroundColor: theme["--canvas"],
    borderColor: theme["--rule"],
    borderRadius: 7,
    borderStyle: "solid",
    borderWidth: 1,
    display: "flex",
    flex: 1,
    minWidth: 0,
  },
  button: {
    WebkitAppRegion: "no-drag",
    alignItems: "center",
    backgroundColor: { ":hover:not(:disabled)": theme["--surface-muted"], default: "transparent" },
    borderColor: {
      "@media (forced-colors: active)": { ":focus-visible": "Highlight", default: "transparent" },
      default: "transparent",
    },
    borderRadius: 5,
    borderStyle: "solid",
    borderWidth: { "@media (forced-colors: active)": 2, default: 0 },
    boxShadow: { ":focus-visible": `inset 0 0 0 2px ${theme["--focus"]}`, default: "none" },
    color: theme["--ink"],
    cursor: { ":disabled": "default", default: "pointer" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 400,
    gap: 6,
    justifyContent: "center",
    minHeight: 30,
    opacity: { ":disabled": 0.4, default: 1 },
    outlineStyle: "none",
    padding: "4px 8px",
  },
  conversation: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr) auto",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  empty: {
    alignItems: "center",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    minHeight: 0,
    overflowY: "auto",
    padding: "24px 20px",
    textAlign: "center",
  },
  emptyDescription: {
    color: theme["--muted"],
    fontSize: 13,
    lineHeight: 1.6,
    margin: "8px 0 0",
    maxWidth: 280,
    textWrap: "pretty",
  },
  emptyIcon: { color: theme["--muted"], flexShrink: 0, marginBottom: 16 },
  emptyTitle: {
    color: theme["--ink"],
    fontSize: 15,
    fontWeight: 500,
    lineHeight: 1.4,
    margin: 0,
    textWrap: "balance",
  },
  error: {
    alignItems: "center",
    backgroundColor: theme["--danger-soft"],
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    padding: "8px 12px",
  },
  errorMessage: {
    color: theme["--danger"],
    flex: 1,
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
    minWidth: 160,
  },
  errorNotice: { color: theme["--danger"] },
  guest: { display: "flex", flex: 1, minHeight: 0, width: "100%" },
  hidden: { display: "none" },
  iconButton: { padding: 0, width: 30 },
  loadStatus: {
    ":empty": { display: "none" },
    color: theme["--muted"],
    fontSize: 12,
    padding: "4px 12px",
  },
  navigation: { borderWidth: 0, display: "flex", flexShrink: 0, gap: 1, margin: 0, padding: 0 },
  notice: {
    fontSize: 13,
    lineHeight: 1.5,
    margin: 0,
    overflowWrap: "anywhere",
    padding: "8px 12px",
  },
  page: { display: "flex", flex: 1, flexDirection: "column", minHeight: 0, minWidth: 0 },
  panel: {
    "@container browser-workspace (max-width: 820px)": {
      borderBottomColor: theme["--rule"],
      borderBottomStyle: "solid",
      borderBottomWidth: 1,
      borderInlineEndWidth: 0,
    },
    backgroundColor: theme["--canvas"],
    borderInlineEndColor: theme["--rule"],
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: 1,
    containerName: "browser",
    containerType: "inline-size",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
  },
  panelHeader: {
    WebkitAppRegion: "drag",
    alignItems: "center",
    backgroundColor: theme["--surface"],
    display: "flex",
    flexShrink: 0,
    gap: 3,
    minHeight: 40,
    paddingBlock: 4,
    paddingBlockStart: shellLayout.headerTopInset,
    paddingInlineEnd: 6,
    paddingInlineStart: shellLayout.headerInset,
  },
  retry: { backgroundColor: theme["--surface"], paddingInline: 12 },
  selected: { backgroundColor: theme["--canvas"], boxShadow: `inset 0 -2px ${theme["--ink"]}` },
  split: {
    display: "grid",
    flex: 1,
    gridTemplateColumns: "minmax(0, 1fr)",
    minHeight: 0,
    minWidth: 0,
  },
  splitOpen: {
    gridTemplateColumns: {
      "@container browser-workspace (max-width: 820px)": "minmax(0, 1fr)",
      default: "minmax(320px, 0.9fr) minmax(400px, 1.1fr)",
    },
    gridTemplateRows: {
      "@container browser-workspace (max-width: 820px)":
        "minmax(100px, min(35%, 260px)) minmax(0, 1fr)",
      default: "minmax(0, 1fr)",
    },
  },
  tab: {
    alignItems: "center",
    borderRadius: "6px 6px 0 0",
    display: "flex",
    flex: "0 0 auto",
    maxWidth: 200,
    minWidth: 116,
  },
  tabButton: { flex: 1, justifyContent: "flex-start", minWidth: 0, textAlign: "start" },
  tabIcon: { flexShrink: 0 },
  tabTitle: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  tabs: {
    alignItems: "stretch",
    display: "flex",
    flex: 1,
    gap: 2,
    minWidth: 0,
    overflowX: "auto",
    scrollbarWidth: "thin",
  },
  toolbar: {
    WebkitAppRegion: "no-drag",
    alignItems: "center",
    backgroundColor: theme["--surface"],
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "flex",
    flexShrink: 0,
    gap: 6,
    minWidth: 0,
    padding: "4px 8px 8px",
  },
  tooltip: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 6,
    borderStyle: "solid",
    borderWidth: 1,
    color: theme["--ink"],
    fontSize: 12,
    lineHeight: 1.5,
    maxWidth: "min(320px, calc(100vw - 24px))",
    overflowWrap: "anywhere",
    padding: "6px 10px",
  },
  tooltipPositioner: { zIndex: 100 },
  workspace: {
    containerName: "browser-workspace",
    containerType: "inline-size",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
  },
})
