import * as stylex from "@stylexjs/stylex"

/** Styles owned by the chat-workspace component. */
export const styles = stylex.create({
  absolute: {"position":"absolute"},
  bgAmber100: {"backgroundColor":"#fef3c7"},
  bgAmber50: {"backgroundColor":"#fffbeb"},
  bgEmerald100: {"backgroundColor":"#d1fae5"},
  bgGradientToT: {"backgroundImage":"linear-gradient(to top, var(--gradient-from), var(--gradient-via), var(--gradient-to))"},
  bgRed100: {"backgroundColor":"#fee2e2"},
  bgRed50: {"backgroundColor":"#fef2f2"},
  bgWhite: {"backgroundColor":"#ffffff"},
  bgZinc200: {"backgroundColor":"#e4e4e7"},
  bgZinc950: {"backgroundColor":"#09090b"},
  borderAmber200: {"borderColor":"#fde68a"},
  borderB: {"borderBottomWidth":1,"borderBottomStyle":"solid"},
  borderRed200: {"borderColor":"#fecaca"},
  borderZinc20080: {"borderColor":"color-mix(in srgb, #e4e4e7 80%, transparent)"},
  bottom0: {"bottom":0},
  bottomFull: {"bottom":"100%"},
  darkBgAmber950: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#451a03"}},
  darkBgEmerald950: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#022c22"}},
  darkBgRed950: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#450a0a"}},
  darkBgZinc50: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#fafafa"}},
  darkBgZinc700: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#3f3f46"}},
  darkBgZinc900: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#18181b"}},
  darkBorderAmber900: {"@media (prefers-color-scheme: dark)":{"borderColor":"#78350f"}},
  darkBorderRed900: {"@media (prefers-color-scheme: dark)":{"borderColor":"#7f1d1d"}},
  darkBorderZinc800: {"@media (prefers-color-scheme: dark)":{"borderColor":"#27272a"}},
  darkFromZinc900: {"@media (prefers-color-scheme: dark)":{"--gradient-from":"#18181b"}},
  darkTextAmber100: {"@media (prefers-color-scheme: dark)":{"color":"#fef3c7"}},
  darkTextAmber300: {"@media (prefers-color-scheme: dark)":{"color":"#fcd34d"}},
  darkTextEmerald300: {"@media (prefers-color-scheme: dark)":{"color":"#6ee7b7"}},
  darkTextRed100: {"@media (prefers-color-scheme: dark)":{"color":"#fee2e2"}},
  darkTextRed300: {"@media (prefers-color-scheme: dark)":{"color":"#fca5a5"}},
  darkTextZinc100: {"@media (prefers-color-scheme: dark)":{"color":"#f4f4f5"}},
  darkTextZinc200: {"@media (prefers-color-scheme: dark)":{"color":"#e4e4e7"}},
  darkTextZinc50: {"@media (prefers-color-scheme: dark)":{"color":"#fafafa"}},
  darkTextZinc950: {"@media (prefers-color-scheme: dark)":{"color":"#09090b"}},
  darkViaZinc90095: {"@media (prefers-color-scheme: dark)":{"--gradient-via":"rgb(24 24 27 / 0.95)"}},
  flex: {"display":"flex"},
  flex1: {"flex":1},
  flexCol: {"flexDirection":"column"},
  fontMedium: {"fontWeight":500},
  fontSemibold: {"fontWeight":600},
  fromWhite: {"--gradient-from":"#fff"},
  gap2: {"gap":"0.5rem"},
  gap3: {"gap":"0.75rem"},
  gap7: {"gap":"1.75rem"},
  grid: {"display":"grid"},
  h48px: {"height":"48px"},
  hFull: {"height":"100%"},
  inset0: {"inset":"0rem"},
  insetX0: {"left":0,"right":0},
  itemsCenter: {"alignItems":"center"},
  justifyBetween: {"justifyContent":"space-between"},
  leading6: {"lineHeight":"1.5rem"},
  maxW3xl: {"maxWidth":"48rem"},
  mb1: {"marginBottom":"0.25rem"},
  messageColumns: {"gridTemplateColumns":"28px minmax(0,1fr)"},
  minH0: {"minHeight":0},
  minW0: {"minWidth":0},
  mxAuto: {"marginInline":"auto"},
  overflowHidden: {"overflow":"hidden"},
  overflowYAuto: {"overflowY":"auto"},
  pb40: {"paddingBottom":"10rem"},
  pb5: {"paddingBottom":"1.25rem"},
  pb8: {"paddingBottom":"2rem"},
  placeItemsCenter: {"placeItems":"center"},
  pointerEventsAuto: {"pointerEvents":"auto"},
  pointerEventsNone: {"pointerEvents":"none"},
  pt05: {"paddingTop":"0.125rem"},
  pt10: {"paddingTop":"2.5rem"},
  px15: {"paddingInline":"0.375rem"},
  px5: {"paddingInline":"1.25rem"},
  px6: {"paddingInline":"1.5rem"},
  py05: {"paddingBlock":"0.125rem"},
  py10: {"paddingBlock":"2.5rem"},
  py2: {"paddingBlock":"0.5rem"},
  relative: {"position":"relative"},
  roundedFull: {"borderRadius":"9999px"},
  roundedMd: {"borderRadius":"0.375rem"},
  shrink0: {"flexShrink":0},
  size7: {"width":"1.75rem","height":"1.75rem"},
  text10px: {"fontSize":"10px"},
  text11px: {"fontSize":"11px"},
  text15px: {"fontSize":"15px"},
  textAmber700: {"color":"#b45309"},
  textAmber950: {"color":"#451a03"},
  textEmerald700: {"color":"#047857"},
  textRed700: {"color":"#b91c1c"},
  textRed950: {"color":"#450a0a"},
  textSm: {"fontSize":"0.875rem","lineHeight":"1.25rem"},
  textWhite: {"color":"#ffffff"},
  textXs: {"fontSize":"0.75rem","lineHeight":"1rem"},
  textZinc400: {"color":"#a1a1aa"},
  textZinc500: {"color":"#71717a"},
  textZinc700: {"color":"#3f3f46"},
  textZinc800: {"color":"#27272a"},
  textZinc950: {"color":"#09090b"},
  toTransparent: {"--gradient-to":"transparent"},
  trackingTight: {"letterSpacing":"-0.025em"},
  truncate: {"overflow":"hidden","textOverflow":"ellipsis","whiteSpace":"nowrap"},
  viaWhite95: {"--gradient-via":"rgb(255 255 255 / 0.95)"},
  wFull: {"width":"100%"},
  whitespacePreWrap: {"whiteSpace":"pre-wrap"},
  z20: {"zIndex":20},
})
