import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

/** Styles owned by this surface, including its responsive and interaction states. */
export const styles = stylex.create({
  chatWorkspace: {
    backgroundColor: theme["--surface"],
    color: theme["--ink"],
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: "0",
    minWidth: "0",
    overflow: "hidden",
  },
  composerDock: {
    backgroundColor: theme["--surface"],
    flex: "0 0 auto",
    maxHeight: "60dvh",
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: "14px 28px max(18px, env(safe-area-inset-bottom))",
    paddingBottom: {
      "@media (max-width: 720px)": "max(8px, env(safe-area-inset-bottom))",
      default: null,
    },
    paddingInline: {
      "@media (max-width: 720px)": "14px",
      default: null,
    },
    pointerEvents: "none",
    position: "relative",
    zIndex: "10",
  },
  composerPlacement: {
    pointerEvents: "none",
  },
  composerPlacementHero: {
    backgroundColor: "transparent",
    maxHeight: "none",
    overflowY: "visible",
    padding: "0",
    width: {
      "@media (max-width: 720px)": "min(calc(100% - 32px), 720px)",
      default: "min(calc(100% - 48px), 720px)",
    },
    zIndex: "10",
  },
  conversationPane: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: "0",
    minWidth: "0",
    overflow: "hidden",
    position: "relative",
  },
  creationTitle: { fontSize: 15, fontWeight: 500, marginBlock: 16 },
  draftConversationPane: {
    alignContent: "start",
    display: "grid",
    gap: "22px",
    gridTemplateRows: "auto auto",
    height: {
      "@media (max-width: 720px)": "auto",
      default: "100%",
    },
    justifyItems: "center",
    minHeight: {
      "@media (max-width: 480px)": "max(420px, calc(100dvh - 228px))",
      "@media (max-width: 720px)": "max(420px, calc(100dvh - 254px))",
      default: null,
    },
    overflowY: "auto",
    paddingBlock: {
      "@media (max-width: 720px)": "36px",
      default: "48px",
    },
    paddingBlockStart: {
      "@media (max-width: 720px)": "36px",
      default: "clamp(48px, 16dvh, 180px)",
    },
  },
  draftHeroTitle: {
    color: theme["--ink-strong"],
    fontSize: "clamp(24px, 3vw, 34px)",
    fontWeight: "500",
    letterSpacing: "-0.035em",
    lineHeight: "1.15",
    margin: "0",
    textAlign: "center",
    width: {
      "@media (max-width: 720px)": "min(calc(100% - 32px), 720px)",
      default: "min(calc(100% - 48px), 720px)",
    },
  },
  emptyAgentName: { color: theme["--focus"], fontStyle: "italic" },
  emptyAvatar: {
    display: "inline-flex",
    flexShrink: 0,
    transform: "rotate(7deg)",
  },
  emptyConversation: {
    alignItems: "start",
    display: "flex",
    flexDirection: "column",
    gap: 14,
    textAlign: "start",
    width: {
      "@media (max-width: 720px)": "calc(100% - 32px)",
      default: "min(calc(100% - 48px), 720px)",
    },
  },
  emptyHeading: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 16,
    justifyContent: "flex-start",
    minWidth: 0,
    width: "100%",
  },
  emptyRole: {
    color: theme["--ink"],
    fontSize: 14,
    lineHeight: 1.5,
    maxWidth: "42ch",
    overflowWrap: "anywhere",
  },
  emptyTitle: {
    color: theme["--ink-strong"],
    fontFamily: '"gelica", Georgia, serif',
    fontSize: "clamp(32px, 4.8vw, 48px)",
    fontWeight: 500,
    letterSpacing: "-0.045em",
    lineHeight: 1.08,
    margin: 0,
    maxWidth: "19ch",
    minWidth: 0,
    overflowWrap: "anywhere",
    textWrap: "balance",
  },
  emptyWorkspace: {
    alignItems: "center",
    backgroundColor: theme["--surface-muted"],
    borderRadius: 8,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    color: theme["--muted"],
    cursor: "pointer",
    display: "flex",
    fontSize: 13,
    gap: 7,
    maxWidth: "100%",
    minHeight: 40,
    overflowWrap: "anywhere",
    paddingInline: 8,
  },
  errorDescription: {
    color: theme["--muted"],
    fontSize: "13px",
    lineHeight: "1.6",
    marginTop: "12px",
    maxWidth: "52ch",
  },
  openError: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    padding: "42px 24px",
    textAlign: "center",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: theme["--surface-muted"],
    borderColor: theme["--rule-strong"],
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: theme["--ink"],
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "13px",
    fontWeight: "760",
    gap: "8px",
    justifyContent: "center",
    marginTop: "18px",
    minHeight: "42px",
    padding: "0 15px",
  },
  sessionStage: {
    display: "grid",
    gridTemplateRows: "minmax(0, 1fr)",
    height: "100%",
    minHeight: "0",
    minWidth: "0",
  },
  sessionStageDraft: {
    display: "block",
  },
  workspaceContent: {
    flex: "1",
    minHeight: "0",
    minWidth: "0",
    overflow: "hidden",
    overflowY: {
      "@media (max-width: 720px)": "auto",
      default: null,
    },
    position: "relative",
  },
  workspaceDetails: { color: theme["--muted"], maxWidth: "100%" },
  workspacePath: { fontSize: 13, lineHeight: 1.5, overflowWrap: "anywhere", paddingBlock: 8 },
})
