import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

/** Styles owned by this surface, including its responsive and interaction states. */
export const styles = stylex.create({
  creationTitle: { fontSize: 15, fontWeight: 500, marginBlock: 16 },
  chatWorkspace: {
    flex: 1,
    overflow: "hidden",
    display: "flex",
    minWidth: "0",
    minHeight: "0",
    flexDirection: "column",
    backgroundColor: theme["--surface"],
    color: theme["--ink"],
  },
  emptyConversation: { display: "flex", width: { default: "min(calc(100% - 48px), 720px)", "@media (max-width: 720px)": "calc(100% - 32px)" }, flexDirection: "column", alignItems: "start", gap: 14, textAlign: "left" },
  emptyHeading: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 20, width: "100%", minWidth: 0 },
  emptyTitle: { textWrap: "balance", minWidth: 0, maxWidth: "19ch", margin: 0, fontFamily: '"gelica", Georgia, serif', fontSize: "clamp(36px, 4.8vw, 62px)", fontWeight: 500, letterSpacing: "-0.045em", lineHeight: 1.08, color: theme["--ink-strong"], overflowWrap: "anywhere" },
  emptyAgentName: { fontStyle: "italic", color: theme["--focus"] },
  emptyAvatar: { display: "inline-flex", flexShrink: 0, transform: "rotate(7deg)", paddingRight: { default: 24, "@media (max-width: 720px)": 0 } },
  emptyRole: { maxWidth: "42ch", overflowWrap: "anywhere", color: theme["--ink"], fontSize: 14, lineHeight: 1.5 },
  workspaceDetails: { maxWidth: "100%", color: theme["--muted"] },
  workspacePath: { fontSize: 13, lineHeight: 1.5, overflowWrap: "anywhere", paddingBlock: 8 },
  emptyWorkspace: { cursor: "pointer", minHeight: 40, borderRadius: 8, paddingInline: 8, backgroundColor: theme["--surface-muted"], outlineWidth: { default: 0, ":focus-visible": 2 }, outlineStyle: "solid", outlineOffset: 2, outlineColor: { default: theme["--ink"], "@media (forced-colors: active)": "Highlight" }, display: "flex", alignItems: "center", gap: 7, maxWidth: "100%", overflowWrap: "anywhere", color: theme["--muted"], fontSize: 13 },
  workspaceContent: {
    position: "relative",
    minWidth: "0",
    minHeight: "0",
    flex: "1",
    overflow: "hidden",
    overflowY: {
      default: null,
      "@media (max-width: 720px)": "auto",
    },
  },
  openError: {
    display: "flex",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    padding: "42px 24px",
    textAlign: "center",
  },
  errorDescription: {
    maxWidth: "52ch",
    marginTop: "12px",
    color: theme["--muted"],
    fontSize: "13px",
    lineHeight: "1.6",
  },
  secondaryButton: {
    display: "inline-flex",
    minHeight: "42px",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    borderRadius: "10px",
    cursor: "pointer",
    padding: "0 15px",
    fontSize: "13px",
    fontWeight: "760",
    marginTop: "18px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: theme["--rule-strong"],
    backgroundColor: theme["--surface-muted"],
    color: theme["--ink"],
  },
  sessionStage: {
    display: "grid",
    height: "100%",
    minWidth: "0",
    minHeight: "0",
    gridTemplateRows: "minmax(0, 1fr)",
  },
  sessionStageDraft: {
    display: "block",
  },
  conversationPane: {
    position: "relative",
    display: "flex",
    height: "100%",
    minWidth: "0",
    minHeight: "0",
    flexDirection: "column",
    overflow: "hidden",
  },
  draftConversationPane: {
    display: "grid",
    height: {
      default: "100%",
      "@media (max-width: 720px)": "auto",
    },
    alignContent: "start",
    justifyItems: "center",
    gridTemplateRows: "auto auto",
    gap: "22px",
    overflowY: "auto",
    paddingBlock: {
      default: "48px",
      "@media (max-width: 720px)": "36px",
    },
    paddingTop: { default: "max(48px, calc(50dvh - 155px))", "@media (max-width: 720px)": "36px" },
    minHeight: {
      default: null,
      "@media (max-width: 720px)": "max(420px, calc(100dvh - 254px))",
      "@media (max-width: 480px)": "max(420px, calc(100dvh - 228px))",
    },
  },
  draftHeroTitle: {
    width: {
      default: "min(calc(100% - 48px), 720px)",
      "@media (max-width: 720px)": "min(calc(100% - 32px), 719px)",
    },
    margin: "0",
    color: theme["--ink-strong"],
    fontSize: "clamp(24px, 3vw, 34px)",
    fontWeight: "500",
    letterSpacing: "-0.035em",
    lineHeight: "1.15",
    textAlign: "center",
  },
  composerDock: {
    maxHeight: "60dvh",
    overflowY: "auto",
    overscrollBehavior: "contain",
    position: "relative",
    zIndex: "10",
    flex: "0 0 auto",
    padding: "14px 28px max(18px, env(safe-area-inset-bottom))",
    backgroundColor: theme["--surface"],
    pointerEvents: "none",
    paddingInline: {
      default: null,
      "@media (max-width: 720px)": "14px",
    },
    paddingBottom: {
      default: null,
      "@media (max-width: 720px)": "max(8px, env(safe-area-inset-bottom))",
    },
  },
  composerPlacement: {
    pointerEvents: "none",
  },
  composerPlacementHero: {
    maxHeight: "none",
    overflowY: "visible",
    zIndex: "10",
    width: {
      default: "min(calc(100% - 48px), 719px)",
      "@media (max-width: 720px)": "min(calc(100% - 32px), 719px)",
    },
    padding: "0",
    backgroundColor: "transparent",
  },
})
