import * as stylex from "@stylexjs/stylex"

/** Styles owned by the model-picker component. */
export const styles = stylex.create({
  backdropBlurXl: {"backdropFilter":"blur(24px)"},
  bgTransparent: {"backgroundColor":"transparent"},
  bgWhite95: {"backgroundColor":"color-mix(in srgb, #ffffff 95%, transparent)"},
  bgZinc100: {"backgroundColor":"#f4f4f5"},
  bgZinc200: {"backgroundColor":"#e4e4e7"},
  bgZinc900: {"backgroundColor":"#18181b"},
  block: {"display":"block"},
  border: {"borderWidth":1,"borderStyle":"solid"},
  borderB: {"borderBottomWidth":1,"borderBottomStyle":"solid"},
  borderZinc200: {"borderColor":"#e4e4e7"},
  capitalize: {"textTransform":"capitalize"},
  darkBgZinc100: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#f4f4f5"}},
  darkBgZinc800: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#27272a"}},
  darkBgZinc90095: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"color-mix(in srgb, #18181b 95%, transparent)"}},
  darkBorderWhite10: {"@media (prefers-color-scheme: dark)":{"borderColor":"color-mix(in srgb, #ffffff 10%, transparent)"}},
  darkBorderZinc800: {"@media (prefers-color-scheme: dark)":{"borderColor":"#27272a"}},
  darkFocusVisibleBgZinc800: {"@media (prefers-color-scheme: dark)":{":focus-visible":{"backgroundColor":"#27272a"}}},
  darkHoverBgZinc700: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#3f3f46"}}},
  darkHoverBgZinc800: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#27272a"}}},
  darkHoverTextZinc100: {"@media (prefers-color-scheme: dark)":{":hover":{"color":"#f4f4f5"}}},
  darkRingZinc100: {"@media (prefers-color-scheme: dark)":{"boxShadow":"0 0 0 1px #f4f4f5"}},
  darkTextZinc100: {"@media (prefers-color-scheme: dark)":{"color":"#f4f4f5"}},
  darkTextZinc300: {"@media (prefers-color-scheme: dark)":{"color":"#d4d4d8"}},
  darkTextZinc900: {"@media (prefers-color-scheme: dark)":{"color":"#18181b"}},
  disabledCursorNotAllowed: {":disabled":{"cursor":"not-allowed"}},
  disabledOpacity50: {":disabled":{"opacity":0.5}},
  fixed: {"position":"fixed"},
  flex: {"display":"flex"},
  flex1: {"flex":1},
  flexCol: {"flexDirection":"column"},
  focusVisibleBgZinc100: {":focus-visible":{"backgroundColor":"#f4f4f5"}},
  focusVisibleOutline2: {":focus-visible":{"outlineWidth":2,"outlineStyle":"solid"}},
  focusVisibleOutlineNone: {":focus-visible":{"outline":"2px solid transparent","outlineOffset":2}},
  focusVisibleOutlineOffset1: {":focus-visible":{"outlineOffset":1}},
  focusVisibleOutlineZinc500: {":focus-visible":{"outlineColor":"#71717a"}},
  focusWithinRingZinc400: {":focus-within":{"boxShadow":"0 0 0 1px #a1a1aa"}},
  fontMedium: {"fontWeight":500},
  fontSemibold: {"fontWeight":600},
  gap1: {"gap":"0.25rem"},
  gap15: {"gap":"0.375rem"},
  gap2: {"gap":"0.5rem"},
  gap3: {"gap":"0.75rem"},
  grid: {"display":"grid"},
  h52px: {"height":"52px"},
  h7: {"height":"1.75rem"},
  h9: {"height":"2.25rem"},
  hFull: {"height":"100%"},
  hoverBgZinc100: {":hover":{"backgroundColor":"#f4f4f5"}},
  hoverBgZinc200: {":hover":{"backgroundColor":"#e4e4e7"}},
  hoverTextZinc900: {":hover":{"color":"#18181b"}},
  inlineFlex: {"display":"inline-flex"},
  itemsCenter: {"alignItems":"center"},
  justifyCenter: {"justifyContent":"center"},
  leadingNone: {"lineHeight":1},
  maxW48: {"maxWidth":"12rem"},
  minH0: {"minHeight":0},
  minW0: {"minWidth":0},
  minWMax: {"minWidth":"max-content"},
  outlineNone: {"outline":"2px solid transparent","outlineOffset":2},
  overflowHidden: {"overflow":"hidden"},
  overflowXAuto: {"overflowX":"auto"},
  overflowYAuto: {"overflowY":"auto"},
  overflowYHidden: {"overflowY":"hidden"},
  p15: {"padding":"0.375rem"},
  p2: {"padding":"0.5rem"},
  pb1: {"paddingBottom":"0.25rem"},
  placeItemsCenter: {"placeItems":"center"},
  placeholderTextZinc400: {"::placeholder":{"color":"#a1a1aa"}},
  pt2: {"paddingTop":"0.5rem"},
  px2: {"paddingInline":"0.5rem"},
  px25: {"paddingInline":"0.625rem"},
  px3: {"paddingInline":"0.75rem"},
  py2: {"paddingBlock":"0.5rem"},
  py8: {"paddingBlock":"2rem"},
  relative: {"position":"relative"},
  ringZinc900: {"boxShadow":"0 0 0 1px #18181b"},
  rounded: {"borderRadius":"0.25rem"},
  roundedLg: {"borderRadius":"0.5rem"},
  roundedMd: {"borderRadius":"0.375rem"},
  roundedXl: {"borderRadius":"0.75rem"},
  shadow2xl: {"boxShadow":"0 25px 50px -12px rgb(0 0 0 / 0.25)"},
  shrink0: {"flexShrink":0},
  size35: {"width":"0.875rem","height":"0.875rem"},
  size4: {"width":"1rem","height":"1rem"},
  size7: {"width":"1.75rem","height":"1.75rem"},
  size9: {"width":"2.25rem","height":"2.25rem"},
  text10px: {"fontSize":"10px"},
  text11px: {"fontSize":"11px"},
  text9px: {"fontSize":"9px"},
  textCenter: {"textAlign":"center"},
  textLeft: {"textAlign":"left"},
  textSm: {"fontSize":"0.875rem","lineHeight":"1.25rem"},
  textWhite: {"color":"#ffffff"},
  textXs: {"fontSize":"0.75rem","lineHeight":"1rem"},
  textZinc400: {"color":"#a1a1aa"},
  textZinc500: {"color":"#71717a"},
  textZinc600: {"color":"#52525b"},
  textZinc900: {"color":"#18181b"},
  trackingWide: {"letterSpacing":"0.025em"},
  transition: {"transitionDuration":"150ms","transitionProperty":"color, background-color, border-color, opacity, box-shadow, transform"},
  truncate: {"overflow":"hidden","textOverflow":"ellipsis","whiteSpace":"nowrap"},
  uppercase: {"textTransform":"uppercase"},
  wFull: {"width":"100%"},
  z100: {"zIndex":100},
})
