import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"
const popupIn = stylex.keyframes({
  from: {
    opacity: "0",
    transform: "translateY(4px)",
  },
  to: {
    opacity: "1",
    transform: "translateY(0)",
  },
})
/** Styles owned by this surface, including its responsive and interaction states. */
export const styles = stylex.create({
  modelPicker: {
    position: "relative",
    minWidth: "0",
  },
  modelTrigger: {
    display: "inline-flex",
    maxWidth: {
      default: "220px",
      "@media (max-width: 480px)": "150px",
    },
    minHeight: "34px",
    minWidth: "0",
    alignItems: "center",
    gap: "7px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "transparent",
      ":hover:not(:disabled)": theme["--rule"],
      ':is([aria-expanded="true"])': theme["--rule"],
    },
    borderRadius: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover:not(:disabled)": theme["--surface-muted"],
      ':is([aria-expanded="true"])': theme["--surface-muted"],
    },
    color: {
      default: theme["--muted"],
      ":hover:not(:disabled)": theme["--ink"],
      ':is([aria-expanded="true"])': theme["--ink"],
    },
    cursor: "pointer",
    padding: "6px 10px",
    fontSize: "11px",
    opacity: {
      default: null,
      ":disabled": "0.5",
    },
  },
  modelTriggerLabel: {
    minWidth: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  modelPopup: {
    position: "fixed",
    zIndex: "40",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: theme["--rule"],
    borderRadius: "12px",
    backgroundColor: theme["--surface"],
    color: theme["--ink"],
    boxShadow: "0 22px 54px -22px rgb(43 26 7 / 0.48)",
    animationName: popupIn,
    animationDuration: "150ms",
    animationTimingFunction: "ease-out",
    animationIterationCount: "1",
  },
  modelSearch: {
    display: "flex",
    alignItems: "center",
    gap: "9px",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: theme["--rule"],
    padding: "10px 12px",
    color: theme["--muted"],
  },
  modelSearchInput: {
    minWidth: "0",
    height: "34px",
    flex: "1",
    borderWidth: "0",
    borderStyle: "solid",
    backgroundColor: "transparent",
    color: theme["--ink-strong"],
    outlineStyle: "none",
    fontSize: "13px",
    "::placeholder": {
      color: theme["--faint"],
    },
  },
  providerFilters: {
    display: "flex",
    minHeight: "50px",
    alignItems: "center",
    gap: "6px",
    overflowX: "auto",
    borderBottomWidth: "1px",
    borderBottomStyle: "solid",
    borderBottomColor: theme["--rule"],
    padding: "7px 10px",
  },
  providerFilter: {
    display: "grid",
    width: "34px",
    height: "34px",
    flex: "0 0 auto",
    placeItems: "center",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: theme["--rule"],
      ':is([aria-pressed="true"])': theme["--ink"],
    },
    borderRadius: "8px",
    backgroundColor: {
      default: theme["--surface-muted"],
      ':is([aria-pressed="true"])': theme["--ink"],
    },
    color: {
      default: theme["--muted"],
      ':is([aria-pressed="true"])': theme["--surface"],
    },
    cursor: "pointer",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "10px",
    fontWeight: "800",
    textTransform: "uppercase",
  },
  hiddenModelsToggle: {
    alignSelf: "flex-start",
    margin: "7px 10px 0",
    borderWidth: "0",
    borderStyle: "solid",
    backgroundColor: "transparent",
    color: {
      default: theme["--muted"],
      ":hover": theme["--ink"],
      ":focus-visible": theme["--ink"],
    },
    cursor: "pointer",
    fontSize: "10px",
  },
  modelOptions: {
    minHeight: "0",
    overflowY: "auto",
    padding: "6px",
  },
  providerName: {
    margin: "0",
    padding: "8px 8px 5px",
    color: theme["--muted"],
    fontSize: "10px",
    fontWeight: "780",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  modelOptionRow: {
    display: "flex",
    alignItems: "center",
    borderRadius: "7px",
    transition: "background-color 100ms ease-out",
    backgroundColor: {
      default: "transparent",
      ":hover": theme["--surface-muted"],
      ":focus-within": theme["--surface-muted"],
      ':has(> [role="option"][aria-selected="true"])': theme["--surface-muted"],
    },
  },
  modelOptionRowHidden: {
    opacity: "0.55",
  },
  modelOption: {
    display: "flex",
    width: "100%",
    minHeight: "44px",
    alignItems: "center",
    gap: "9px",
    borderWidth: "0",
    borderStyle: "solid",
    borderRadius: "9px",
    backgroundColor: "transparent",
    cursor: "pointer",
    padding: "5px 8px",
    textAlign: "left",
    transition: "background-color 100ms ease-out, color 100ms ease-out, scale 150ms ease-out",
    scale: {
      default: null,
      ":active": "0.96",
    },
  },
  rowOption: {
    width: "auto",
    minWidth: "0",
    flex: "1",
  },
  modelOptionCopy: {
    display: "flex",
    minWidth: "0",
    flex: "1",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  modelOptionLabel: {
    display: "flex",
    minWidth: "0",
    alignItems: "baseline",
    gap: "7px",
  },
  modelName: {
    overflow: "hidden",
    color: theme["--ink-strong"],
    fontSize: "13px",
    fontWeight: "680",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  modelTier: {
    flex: "0 0 auto",
    color: theme["--muted"],
    fontSize: "10px",
    fontWeight: "520",
  },
  selectedIcon: {
    color: theme["--accent"],
  },
  modelEffortControl: {
    display: "flex",
    flexShrink: "0",
    minHeight: "52px",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
    padding: "8px 12px",
    borderTopWidth: "1px",
    borderTopStyle: "solid",
    borderTopColor: theme["--rule"],
    color: theme["--muted"],
    fontSize: "12px",
  },
  effortTrigger: {
    minWidth: "82px",
  },
  modelOptionPin: {
    scale: {
      default: null,
      ":active": "0.96",
    },
    display: "grid",
    width: "30px",
    height: "34px",
    flex: "0 0 auto",
    placeItems: "center",
    borderWidth: "0",
    borderStyle: "solid",
    borderRadius: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": theme["--surface"],
    },
    color: {
      default: theme["--muted"],
      ":hover": theme["--accent"],
      ':is([aria-pressed="true"])': theme["--accent"],
    },
    cursor: "pointer",
    opacity: {
      default: "0",
      ":focus-visible": "1",
      ':is([aria-pressed="true"])': "1",
      [stylex.when.ancestor(":hover")]: 1,
      [stylex.when.ancestor(":focus-within")]: 1,
      "@media (hover: none)": "1",
    },
    transition:
      "background-color 100ms ease-out, color 100ms ease-out, opacity 100ms ease-out, scale 150ms ease-out",
  },
  modelOptionHide: {
    scale: {
      default: null,
      ":active": "0.96",
    },
    display: "grid",
    width: "30px",
    height: "34px",
    flex: "0 0 auto",
    placeItems: "center",
    borderWidth: "0",
    borderStyle: "solid",
    borderRadius: "8px",
    backgroundColor: {
      default: "transparent",
      ":hover": theme["--surface"],
    },
    color: {
      default: theme["--muted"],
      ":hover": theme["--accent"],
    },
    cursor: "pointer",
    opacity: {
      default: "0",
      ":focus-visible": "1",
      [stylex.when.ancestor(":hover")]: 1,
      [stylex.when.ancestor(":focus-within")]: 1,
      "@media (hover: none)": "1",
    },
    transition:
      "background-color 100ms ease-out, color 100ms ease-out, opacity 100ms ease-out, scale 150ms ease-out",
  },
  modelEmpty: {
    display: "grid",
    justifyItems: "center",
    gap: "12px",
    margin: "0",
    padding: "34px 18px",
    color: theme["--muted"],
    textAlign: "center",
    fontSize: "12px",
  },
  modelEmptyAction: {
    minHeight: "32px",
    padding: "0 11px",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: theme["--rule"],
    borderRadius: "8px",
    color: theme["--ink"],
    backgroundColor: { default: "transparent", ":hover": theme["--surface"] },
  },
})
