import * as stylex from "@stylexjs/stylex"

/** Styles owned by the prime-empty-state component. */
export const styles = stylex.create({
  absolute: {"position":"absolute"},
  bgWhite: {"backgroundColor":"#ffffff"},
  bgZinc900: {"backgroundColor":"#18181b"},
  border: {"borderWidth":1,"borderStyle":"solid"},
  borderZinc200: {"borderColor":"#e4e4e7"},
  darkBgZinc100: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#f4f4f5"}},
  darkBgZinc900: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#18181b"}},
  darkBorderZinc700: {"@media (prefers-color-scheme: dark)":{"borderColor":"#3f3f46"}},
  darkBorderZinc800: {"@media (prefers-color-scheme: dark)":{"borderColor":"#27272a"}},
  darkHoverBgWhite: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#ffffff"}}},
  darkTextRed400: {"@media (prefers-color-scheme: dark)":{"color":"#f87171"}},
  darkTextZinc200: {"@media (prefers-color-scheme: dark)":{"color":"#e4e4e7"}},
  darkTextZinc300: {"@media (prefers-color-scheme: dark)":{"color":"#d4d4d8"}},
  darkTextZinc400: {"@media (prefers-color-scheme: dark)":{"color":"#a1a1aa"}},
  darkTextZinc50: {"@media (prefers-color-scheme: dark)":{"color":"#fafafa"}},
  darkTextZinc950: {"@media (prefers-color-scheme: dark)":{"color":"#09090b"}},
  disabledCursorWait: {":disabled":{"cursor":"wait"}},
  disabledOpacity60: {":disabled":{"opacity":0.6}},
  flex: {"display":"flex"},
  flexCol: {"flexDirection":"column"},
  focusVisibleOutline2: {":focus-visible":{"outlineWidth":2,"outlineStyle":"solid"}},
  focusVisibleOutlineOffset2: {":focus-visible":{"outlineOffset":2}},
  focusVisibleOutlineZinc500: {":focus-visible":{"outlineColor":"#71717a"}},
  fontMedium: {"fontWeight":500},
  fontSemibold: {"fontWeight":600},
  gap2: {"gap":"0.5rem"},
  grid: {"display":"grid"},
  h9: {"height":"2.25rem"},
  hFull: {"height":"100%"},
  hoverBgZinc700: {":hover":{"backgroundColor":"#3f3f46"}},
  inlineFlex: {"display":"inline-flex"},
  inset0: {"inset":"0rem"},
  inset1: {"inset":"0.25rem"},
  itemsCenter: {"alignItems":"center"},
  justifyCenter: {"justifyContent":"center"},
  leading6: {"lineHeight":"1.5rem"},
  maxWMd: {"maxWidth":"28rem"},
  maxWSm: {"maxWidth":"24rem"},
  mb7: {"marginBottom":"1.75rem"},
  minH0: {"minHeight":0},
  mt2: {"marginTop":"0.5rem"},
  mt3: {"marginTop":"0.75rem"},
  mt6: {"marginTop":"1.5rem"},
  negativeRotate8: {"transform":"rotate(-8deg)"},
  placeItemsCenter: {"placeItems":"center"},
  px35: {"paddingInline":"0.875rem"},
  px6: {"paddingInline":"1.5rem"},
  py12: {"paddingBlock":"3rem"},
  relative: {"position":"relative"},
  rotate8: {"transform":"rotate(8deg)"},
  roundedLg: {"borderRadius":"0.5rem"},
  roundedXl: {"borderRadius":"0.75rem"},
  shadowSm: {"boxShadow":"0 1px 2px 0 rgb(0 0 0 / 0.05)"},
  size11: {"width":"2.75rem","height":"2.75rem"},
  size4: {"width":"1rem","height":"1rem"},
  size5: {"width":"1.25rem","height":"1.25rem"},
  textCenter: {"textAlign":"center"},
  textRed700: {"color":"#b91c1c"},
  textSm: {"fontSize":"0.875rem","lineHeight":"1.25rem"},
  textWhite: {"color":"#ffffff"},
  textXl: {"fontSize":"1.25rem","lineHeight":"1.75rem"},
  textXs: {"fontSize":"0.75rem","lineHeight":"1rem"},
  textZinc500: {"color":"#71717a"},
  textZinc700: {"color":"#3f3f46"},
  textZinc950: {"color":"#09090b"},
  trackingTight: {"letterSpacing":"-0.025em"},
  transition: {"transitionDuration":"150ms","transitionProperty":"color, background-color, border-color, opacity, box-shadow, transform"},
})
