import * as stylex from "@stylexjs/stylex"

/** Styles owned by the prime-composer component. */
export const styles = stylex.create({
  backdropBlurXl: {"backdropFilter":"blur(24px)"},
  bgCurrent: {"backgroundColor":"currentColor"},
  bgTransparent: {"backgroundColor":"transparent"},
  bgWhite95: {"backgroundColor":"color-mix(in srgb, #ffffff 95%, transparent)"},
  bgZinc30080: {"backgroundColor":"color-mix(in srgb, #d4d4d8 80%, transparent)"},
  bgZinc900: {"backgroundColor":"#18181b"},
  composerShadow: {"boxShadow":"0 12px 28px -18px rgba(0,0,0,0.4)"},
  darkBgWhite10: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"color-mix(in srgb, #ffffff 10%, transparent)"}},
  darkBgZinc100: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#f4f4f5"}},
  darkBgZinc95095: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"color-mix(in srgb, #09090b 95%, transparent)"}},
  darkDisabledBgZinc800: {"@media (prefers-color-scheme: dark)":{":disabled":{"backgroundColor":"#27272a"}}},
  darkDisabledTextZinc600: {"@media (prefers-color-scheme: dark)":{":disabled":{"color":"#52525b"}}},
  darkFocusWithinBgWhite20: {"@media (prefers-color-scheme: dark)":{":focus-within":{"backgroundColor":"color-mix(in srgb, #ffffff 20%, transparent)"}}},
  darkHoverBgWhite: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#ffffff"}}},
  darkPlaceholderTextZinc600: {"@media (prefers-color-scheme: dark)":{"::placeholder":{"color":"#52525b"}}},
  darkShadowNone: {"@media (prefers-color-scheme: dark)":{"boxShadow":"none"}},
  darkTextZinc100: {"@media (prefers-color-scheme: dark)":{"color":"#f4f4f5"}},
  darkTextZinc950: {"@media (prefers-color-scheme: dark)":{"color":"#09090b"}},
  disabledBgZinc200: {":disabled":{"backgroundColor":"#e4e4e7"}},
  disabledCursorNotAllowed: {":disabled":{"cursor":"not-allowed"}},
  disabledOpacity50: {":disabled":{"opacity":0.5}},
  disabledTextZinc400: {":disabled":{"color":"#a1a1aa"}},
  flex: {"display":"flex"},
  focusVisibleOutline2: {":focus-visible":{"outlineWidth":2,"outlineStyle":"solid"}},
  focusVisibleOutlineOffset2: {":focus-visible":{"outlineOffset":2}},
  focusVisibleOutlineZinc500: {":focus-visible":{"outlineColor":"#71717a"}},
  focusWithinBgZinc400: {":focus-within":{"backgroundColor":"#a1a1aa"}},
  gap3: {"gap":"0.75rem"},
  grid: {"display":"grid"},
  hoverBgZinc700: {":hover":{"backgroundColor":"#3f3f46"}},
  itemsCenter: {"alignItems":"center"},
  justifyBetween: {"justifyContent":"space-between"},
  leading6: {"lineHeight":"1.5rem"},
  maxW3xl: {"maxWidth":"48rem"},
  minH68px: {"minHeight":"68px"},
  minW0: {"minWidth":0},
  mt1: {"marginTop":"0.25rem"},
  mxAuto: {"marginInline":"auto"},
  outlineNone: {"outline":"2px solid transparent","outlineOffset":2},
  pPx: {"padding":1},
  pb3: {"paddingBottom":"0.75rem"},
  placeItemsCenter: {"placeItems":"center"},
  placeholderTextZinc400: {"::placeholder":{"color":"#a1a1aa"}},
  pt3: {"paddingTop":"0.75rem"},
  px1: {"paddingInline":"0.25rem"},
  px3: {"paddingInline":"0.75rem"},
  resizeNone: {"resize":"none"},
  rounded21px: {"borderRadius":"21px"},
  rounded22px: {"borderRadius":"22px"},
  rounded2px: {"borderRadius":"2px"},
  roundedFull: {"borderRadius":"9999px"},
  shrink0: {"flexShrink":0},
  size25: {"width":"0.625rem","height":"0.625rem"},
  size4: {"width":"1rem","height":"1rem"},
  size8: {"width":"2rem","height":"2rem"},
  srOnly: {"position":"absolute","width":1,"height":1,"padding":0,"margin":-1,"overflow":"hidden","clip":"rect(0, 0, 0, 0)","whiteSpace":"nowrap","borderWidth":0},
  text15px: {"fontSize":"15px"},
  textWhite: {"color":"#ffffff"},
  textZinc900: {"color":"#18181b"},
  transition: {"transitionDuration":"150ms","transitionProperty":"color, background-color, border-color, opacity, box-shadow, transform"},
  transitionColors: {"transitionDuration":"150ms","transitionProperty":"color, background-color, border-color"},
  wFull: {"width":"100%"},
})
