import * as stylex from "@stylexjs/stylex"

/** Styles owned by the sidebar component. */
export const styles = stylex.create({
  bgAmber500: {"backgroundColor":"#f59e0b"},
  bgEmerald500: {"backgroundColor":"#10b981"},
  bgZinc20075: {"backgroundColor":"color-mix(in srgb, #e4e4e7 75%, transparent)"},
  bgZinc300: {"backgroundColor":"#d4d4d8"},
  bgZinc50: {"backgroundColor":"#fafafa"},
  borderR: {"borderRightWidth":1,"borderRightStyle":"solid"},
  borderT: {"borderTopWidth":1,"borderTopStyle":"solid"},
  borderZinc20080: {"borderColor":"color-mix(in srgb, #e4e4e7 80%, transparent)"},
  darkBgZinc700: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#3f3f46"}},
  darkBgZinc800: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#27272a"}},
  darkBgZinc950: {"@media (prefers-color-scheme: dark)":{"backgroundColor":"#09090b"}},
  darkBorderZinc800: {"@media (prefers-color-scheme: dark)":{"borderColor":"#27272a"}},
  darkHoverBgZinc800: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#27272a"}}},
  darkHoverBgZinc900: {"@media (prefers-color-scheme: dark)":{":hover":{"backgroundColor":"#18181b"}}},
  darkHoverTextWhite: {"@media (prefers-color-scheme: dark)":{":hover":{"color":"#ffffff"}}},
  darkHoverTextZinc100: {"@media (prefers-color-scheme: dark)":{":hover":{"color":"#f4f4f5"}}},
  darkHoverTextZinc300: {"@media (prefers-color-scheme: dark)":{":hover":{"color":"#d4d4d8"}}},
  darkTextZinc400: {"@media (prefers-color-scheme: dark)":{"color":"#a1a1aa"}},
  darkTextZinc50: {"@media (prefers-color-scheme: dark)":{"color":"#fafafa"}},
  darkTextZinc600: {"@media (prefers-color-scheme: dark)":{"color":"#52525b"}},
  flex: {"display":"flex"},
  flex1: {"flex":1},
  flexCol: {"flexDirection":"column"},
  focusVisibleOutline2: {":focus-visible":{"outlineWidth":2,"outlineStyle":"solid"}},
  focusVisibleOutlineOffset1: {":focus-visible":{"outlineOffset":1}},
  focusVisibleOutlineOffset2: {":focus-visible":{"outlineOffset":2}},
  focusVisibleOutlineZinc500: {":focus-visible":{"outlineColor":"#71717a"}},
  fontMedium: {"fontWeight":500},
  gap2: {"gap":"0.5rem"},
  grid: {"display":"grid"},
  h35: {"height":"0.875rem"},
  h52px: {"height":"52px"},
  h8: {"height":"2rem"},
  hScreen: {"height":"100vh"},
  hoverBgZinc20055: {":hover":{"backgroundColor":"color-mix(in srgb, #e4e4e7 55%, transparent)"}},
  hoverBgZinc20070: {":hover":{"backgroundColor":"color-mix(in srgb, #e4e4e7 70%, transparent)"}},
  hoverBgZinc20080: {":hover":{"backgroundColor":"color-mix(in srgb, #e4e4e7 80%, transparent)"}},
  hoverTextZinc700: {":hover":{"color":"#3f3f46"}},
  hoverTextZinc950: {":hover":{"color":"#09090b"}},
  itemsCenter: {"alignItems":"center"},
  justifyBetween: {"justifyContent":"space-between"},
  minH0: {"minHeight":0},
  minW0: {"minWidth":0},
  overflowYAuto: {"overflowY":"auto"},
  p2: {"padding":"0.5rem"},
  placeItemsCenter: {"placeItems":"center"},
  px05: {"paddingInline":"0.125rem"},
  px2: {"paddingInline":"0.5rem"},
  px25: {"paddingInline":"0.625rem"},
  px3: {"paddingInline":"0.75rem"},
  py2: {"paddingBlock":"0.5rem"},
  rotate90: {"transform":"rotate(90deg)"},
  roundedFull: {"borderRadius":"9999px"},
  roundedLg: {"borderRadius":"0.5rem"},
  roundedMd: {"borderRadius":"0.375rem"},
  shrink0: {"flexShrink":0},
  size15: {"width":"0.375rem","height":"0.375rem"},
  size3: {"width":"0.75rem","height":"0.75rem"},
  size4: {"width":"1rem","height":"1rem"},
  size7: {"width":"1.75rem","height":"1.75rem"},
  spaceY05: {"display":"flex","flexDirection":"column","rowGap":"0.125rem"},
  textLeft: {"textAlign":"left"},
  textSm: {"fontSize":"0.875rem","lineHeight":"1.25rem"},
  textXs: {"fontSize":"0.75rem","lineHeight":"1rem"},
  textZinc400: {"color":"#a1a1aa"},
  textZinc500: {"color":"#71717a"},
  textZinc600: {"color":"#52525b"},
  textZinc950: {"color":"#09090b"},
  trackingTight: {"letterSpacing":"-0.025em"},
  transition: {"transitionDuration":"150ms","transitionProperty":"color, background-color, border-color, opacity, box-shadow, transform"},
  transitionTransform: {"transitionDuration":"150ms","transitionProperty":"transform"},
  truncate: {"overflow":"hidden","textOverflow":"ellipsis","whiteSpace":"nowrap"},
  w4: {"width":"1rem"},
  wFull: {"width":"100%"},
})
