import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

export const styles = stylex.create({
  actions: { display: "flex", flexWrap: "wrap", gap: 8, justifyContent: "flex-end" },
  button: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-muted"], default: theme["--surface"] },
    borderColor: theme["--rule"],
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    color: theme["--ink"],
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 12,
    gap: 6,
    justifySelf: "start",
    minHeight: 36,
    opacity: { ":disabled": 0.5, default: 1 },
    paddingInline: 10,
  },
  editor: {
    display: "grid",
    gap: 8,
    marginInline: "auto",
    maxWidth: 720,
    paddingBlock: 12,
    width: "100%",
  },
  field: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: theme["--ink"],
    fontSize: 14,
    minHeight: 64,
    padding: 10,
    width: "100%",
  },
  hint: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5, overflowWrap: "anywhere" },
  label: { display: "grid", fontSize: 13, gap: 6 },
  list: { display: "grid", gap: 16, listStyle: "none", margin: 0, padding: 0 },
  note: {
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    paddingBlockEnd: 12,
    whiteSpace: "pre-wrap",
  },
  rail: {
    backgroundColor: theme["--surface"],
    borderTopColor: theme["--rule"],
    borderTopStyle: "solid",
    borderTopWidth: 1,
    flexShrink: 0,
    maxHeight: "40dvh",
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: "6px 16px",
  },
  review: {
    display: "grid",
    fontSize: 13,
    gap: 12,
    marginInline: "auto",
    maxWidth: 720,
    paddingBlock: 12,
  },
  toolbar: {
    WebkitAppRegion: "no-drag",
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    justifyContent: "flex-end",
    minHeight: 36,
  },
})
