import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

export const styles = stylex.create({
  actions: { display: "flex", flexWrap: "wrap", gap: 8, justifyContent: "flex-end" },
  button: {
    alignItems: "center",
    backgroundColor: { ":hover": theme["--surface-muted"], default: theme["--surface"] },
    borderColor: theme["--rule"],
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    boxShadow: { ":focus-visible": "0 0 0 2px var(--focus)", default: null },
    color: theme["--ink"],
    cursor: "pointer",
    display: "inline-flex",
    fontSize: 12,
    gap: 6,
    minHeight: 36,
    paddingInline: 10,
  },
  dialog: { maxWidth: "min(520px, calc(100% - 32px))", zIndex: 110 },
  field: {
    backgroundColor: theme["--surface"],
    borderColor: theme["--rule"],
    borderRadius: 8,
    borderStyle: "solid",
    borderWidth: 1,
    color: theme["--ink"],
    fontSize: 14,
    minHeight: 100,
    padding: 10,
    width: "100%",
  },
  hidden: { display: "none" },
  hint: { color: theme["--muted"], fontSize: 12, lineHeight: 1.5, overflowWrap: "anywhere" },
  label: { display: "grid", gap: 8 },
  list: { display: "grid", gap: 16, listStyle: "none", margin: 0, padding: 0 },
  note: {
    borderBottomColor: theme["--rule"],
    borderBottomStyle: "solid",
    borderBottomWidth: 1,
    display: "grid",
    gap: 8,
    paddingBlockEnd: 12,
    whiteSpace: "pre-wrap",
  },
  toolbar: {
    WebkitAppRegion: "no-drag",
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    insetInlineEnd: 60,
    maxWidth: "calc(100% - 120px)",
    position: "fixed",
    top: 12,
    zIndex: 70,
  },
})
