import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

/** Styles owned by this surface, including its responsive and interaction states. */
export const styles = stylex.create({
  workspacePickerTrigger: {
    display: "inline-flex",
    alignItems: "baseline",
    gap: "5px",
    borderWidth: "0",
    borderStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomStyle: "dotted",
    borderBottomColor: {
      default: theme["--muted"],
      ":hover": theme["--ink-strong"],
      ':is([aria-expanded="true"])': theme["--ink-strong"],
    },
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    padding: "0",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontWeight: "inherit",
    fontStyle: "inherit",
    lineHeight: "inherit",
  },
  workspaceDialog: {
    width: "min(680px, calc(100% - 32px))",
    maxWidth: "680px",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    overscrollBehavior: "contain",
    maxHeight: "min(720px, calc(100dvh - 32px))",
    gap: "12px",
    padding: { default: "24px", "@media (max-width: 480px)": "16px" },
  },
  header: { paddingInlineEnd: 24, flexShrink: 0 },
  searchLabel: { fontSize: 13, fontWeight: 500, marginTop: 8 },
  searchGroup: { flexShrink: 0 },
  searchInput: { fontSize: { default: 14, "@media (max-width: 480px)": 16 } },
  error: { margin: 0, padding: 12, backgroundColor: theme["--surface-muted"], color: theme["--ink"], fontSize: 14, lineHeight: 1.5 },
  optionHeading: { display: "flex", alignItems: "baseline", gap: 8, flexWrap: "wrap" },
  currentLabel: { fontSize: 12, fontWeight: 500, color: theme["--muted"] },
  optionConversation: { fontSize: 13, lineHeight: 1.5, overflowWrap: "anywhere", fontWeight: 400 },
  workspaceDialogSummary: {
    margin: "0",
    color: theme["--muted"],
    fontSize: "12px",
  },
  workspaceDialogList: {
    minHeight: "60px",
    maxHeight: "min(380px, 50dvh)",
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
    padding: "4px",
  },
  workspaceDialogEmpty: {
    margin: "0",
    padding: "24px 8px",
    overflowWrap: "anywhere",
    lineHeight: "1.5",
    color: theme["--muted"],
    fontSize: "14px",
  },
  workspaceDialogOption: {
    display: "flex",
    width: "100%",
    minHeight: "52px",
    height: "auto",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: "12px",
    padding: "12px",
    marginBlockEnd: "4px",
    textAlign: "start",
    whiteSpace: "normal",
  },
  workspaceDialogOptionCurrent: {
    backgroundColor: theme["--focus-soft"],
  },
  optionIcon: {
    width: "16px",
    flex: "0 0 auto",
  },
  optionDetails: {
    display: "grid",
    minWidth: "0",
    flex: "1",
    gap: "3px",
  },
  optionName: {
    overflowWrap: "anywhere",
    whiteSpace: "normal",
    fontSize: "14px",
    lineHeight: "1.4",
  },
  optionPath: {
    overflowWrap: "anywhere",
    whiteSpace: "normal",
    color: theme["--muted"],
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: "12px",
    lineHeight: "1.5",
    fontWeight: "500",
  },
})
