import * as stylex from "@stylexjs/stylex"
import { theme } from "../theme.stylex"

/** Styles owned by this surface, including its responsive and interaction states. */
export const styles = stylex.create({
  currentLabel: { color: theme["--muted"], fontSize: 12, fontWeight: 500 },
  error: {
    backgroundColor: theme["--surface-muted"],
    color: theme["--ink"],
    fontSize: 14,
    lineHeight: 1.5,
    margin: 0,
    padding: 12,
  },
  header: { flexShrink: 0, paddingInlineEnd: 24 },
  optionConversation: { fontSize: 13, fontWeight: 400, lineHeight: 1.5, overflowWrap: "anywhere" },
  optionDetails: {
    display: "grid",
    flex: "1",
    gap: "3px",
    minWidth: "0",
  },
  optionHeading: { alignItems: "baseline", display: "flex", flexWrap: "wrap", gap: 8 },
  optionIcon: {
    flex: "0 0 auto",
    width: "16px",
  },
  optionName: {
    fontSize: "14px",
    lineHeight: "1.4",
    overflowWrap: "anywhere",
    whiteSpace: "normal",
  },
  optionPath: {
    color: theme["--muted"],
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: "12px",
    fontWeight: "500",
    lineHeight: "1.5",
    overflowWrap: "anywhere",
    whiteSpace: "normal",
  },
  searchGroup: { flexShrink: 0 },
  searchInput: { fontSize: { "@media (max-width: 480px)": 16, default: 14 } },
  searchLabel: { fontSize: 13, fontWeight: 500, marginTop: 8 },
  workspaceDialog: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    maxHeight: "min(720px, calc(100dvh - 32px))",
    maxWidth: "680px",
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: { "@media (max-width: 480px)": "16px", default: "24px" },
    width: "min(680px, calc(100% - 32px))",
  },
  workspaceDialogEmpty: {
    color: theme["--muted"],
    fontSize: "14px",
    lineHeight: "1.5",
    margin: "0",
    overflowWrap: "anywhere",
    padding: "24px 8px",
  },
  workspaceDialogList: {
    maxHeight: "min(380px, 50dvh)",
    minHeight: "60px",
    overflowY: "auto",
    overscrollBehavior: "contain",
    padding: "4px",
    scrollbarGutter: "stable",
  },
  workspaceDialogOption: {
    alignItems: "center",
    display: "flex",
    gap: "12px",
    height: "auto",
    justifyContent: "flex-start",
    marginBlockEnd: "4px",
    minHeight: "52px",
    padding: "12px",
    textAlign: "start",
    whiteSpace: "normal",
    width: "100%",
  },
  workspaceDialogOptionCurrent: {
    backgroundColor: theme["--focus-soft"],
  },
  workspaceDialogSummary: {
    color: theme["--muted"],
    fontSize: "12px",
    margin: "0",
  },
  workspacePickerTrigger: {
    alignItems: "baseline",
    backgroundColor: "transparent",
    borderBottomColor: {
      ":hover": theme["--ink-strong"],
      ':is([aria-expanded="true"])': theme["--ink-strong"],
      default: theme["--muted"],
    },
    borderBottomStyle: "dotted",
    borderBottomWidth: "1px",
    borderStyle: "solid",
    borderWidth: "0",
    color: "inherit",
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontStyle: "inherit",
    fontWeight: "inherit",
    gap: "5px",
    lineHeight: "inherit",
    padding: "0",
  },
})
