export {
  agentWorkspaceName,
  connectAgentWorkspaceSession,
  createAgentWithTask,
  projectAgentWorkspaceControls,
  projectAgentWorkspaceFolders,
  selectInitialAgentWorkspace,
  type AgentCreationOutcome,
  type AgentCreationPort,
  type AgentCreationRequest,
  AgentCreationTransportError,
  type AgentWorkspaceComposerController,
  type AgentWorkspaceConnectionController,
  type AgentWorkspaceController,
  type AgentWorkspaceControlSource,
  type AgentWorkspaceControls,
  type AgentWorkspaceConversationController,
  type AgentWorkspaceFolder,
  type AgentWorkspaceGitController,
  type AgentWorkspaceInitialSelection,
  type AgentWorkspaceNavigationController,
  type AgentWorkspaceSelectedIdentity,
  type AgentWorkspaceSpawnedTarget,
  type CreateAgentWithTaskResult,
} from './lib/workspace.js';
export {
  createAgentSessionLifecycle,
  type AgentSessionHistoryCallbacks,
  type AgentSessionHistoryPort,
  type AgentSessionLifecycle,
} from './lib/session-lifecycle.js';
export {
  AgentGitTransportError,
  createAgentGitWorkspaceService,
  type AgentGitTransition,
  type AgentGitWorkspacePort,
  type AgentGitWorkspaceService,
} from './lib/git-workspace.js';
