[package]
name = "ernie-gpui-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ernie-gpui"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui_platform = { workspace = true, features = ["font-kit"] }
ernie-gpui-ui.workspace = true

[lints]
workspace = true
