import * as stylex from "@stylexjs/stylex"

/** Button layout and variants; Base UI state selectors live in primitives.css. */
export const styles = stylex.create({
  root: {
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    backgroundClip: "padding-box",
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    fontWeight: 500,
    whiteSpace: "nowrap",
    userSelect: "none",
    outline: "none",
    transitionProperty: "color, background-color, border-color, box-shadow, transform",
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  primary: { backgroundColor: "var(--primary)", color: "var(--primary-foreground)" },
  outline: {
    borderColor: "var(--border)",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
  },
  secondary: { backgroundColor: "var(--secondary)", color: "var(--secondary-foreground)" },
  ghost: { backgroundColor: "transparent" },
  destructive: {
    backgroundColor: "color-mix(in oklab, var(--destructive) 10%, transparent)",
    color: "var(--destructive)",
  },
  link: { backgroundColor: "transparent", color: "var(--primary)", textUnderlineOffset: 4 },
  normal: { height: 32, gap: 6, paddingInline: 10 },
  xs: {
    height: 24,
    gap: 4,
    borderRadius: "min(var(--radius), 10px)",
    paddingInline: 8,
    fontSize: "0.75rem",
    lineHeight: "1rem",
  },
  sm: {
    height: 28,
    gap: 4,
    borderRadius: "min(var(--radius), 12px)",
    paddingInline: 10,
    fontSize: "0.8rem",
  },
  lg: { height: 36, gap: 6, paddingInline: 10 },
  icon: { width: 32, height: 32 },
  iconXs: { width: 24, height: 24, borderRadius: "min(var(--radius), 10px)" },
  iconSm: { width: 28, height: 28, borderRadius: "min(var(--radius), 12px)" },
  iconLg: { width: 36, height: 36 },
})
