import * as stylex from "@stylexjs/stylex"

/** Dialog geometry; open/closed animations are scoped in primitives.css. */
export const styles = stylex.create({
  overlay: {
    position: "fixed",
    inset: 0,
    isolation: "isolate",
    zIndex: 50,
    backgroundColor: "rgb(0 0 0 / 0.1)",
    backdropFilter: "blur(4px)",
  },
  content: {
    position: "fixed",
    top: "50%",
    insetInlineStart: "50%",
    zIndex: 50,
    display: "grid",
    width: "100%",
    maxWidth: { default: "calc(100% - 2rem)", "@media (min-width: 640px)": "24rem" },
    transform: "translate(-50%, -50%)",
    gap: 16,
    borderRadius: 12,
    backgroundColor: "var(--popover)",
    padding: 16,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    color: "var(--popover-foreground)",
    boxShadow: "0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent)",
    outline: "none",
  },
  close: { position: "absolute", top: 8, insetInlineEnd: 8 },
  header: { display: "flex", flexDirection: "column", gap: 8 },
  footer: {
    marginInline: -16,
    marginBottom: -16,
    display: "flex",
    flexDirection: { default: "column-reverse", "@media (min-width: 640px)": "row" },
    justifyContent: { default: null, "@media (min-width: 640px)": "flex-end" },
    gap: 8,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    backgroundColor: "color-mix(in oklab, var(--shadcn-muted) 50%, transparent)",
    padding: 16,
  },
  title: { fontSize: "1rem", lineHeight: 1, fontWeight: 500 },
  description: { fontSize: "0.875rem", lineHeight: "1.25rem", color: "var(--muted-foreground)" },
})
