import * as stylex from "@stylexjs/stylex"

/** Input-group layout and addon sizes, composed before caller overrides. */
export const styles = stylex.create({
  root: {
    position: "relative",
    display: "flex",
    height: 32,
    width: "100%",
    minWidth: 0,
    alignItems: "center",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--input)",
    outline: "none",
    transitionProperty: "color, background-color, border-color, box-shadow",
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  addon: {
    display: "flex",
    height: "auto",
    cursor: "text",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingBlock: 6,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    fontWeight: 500,
    color: "var(--muted-foreground)",
    userSelect: "none",
  },
  inlineStart: { order: -9999, paddingInlineStart: 8 },
  inlineEnd: { order: 9999, paddingInlineEnd: 8 },
  blockStart: {
    order: -9999,
    width: "100%",
    justifyContent: "flex-start",
    paddingInline: 10,
    paddingTop: 8,
  },
  blockEnd: {
    order: 9999,
    width: "100%",
    justifyContent: "flex-start",
    paddingInline: 10,
    paddingBottom: 8,
  },
  button: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    boxShadow: "none",
  },
  xs: { height: 24, gap: 4, borderRadius: "calc(var(--radius) - 3px)", paddingInline: 6 },
  iconXs: { width: 24, height: 24, borderRadius: "calc(var(--radius) - 3px)", padding: 0 },
  iconSm: { width: 32, height: 32, padding: 0 },
  text: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    color: "var(--muted-foreground)",
  },
})
