import * as stylex from "@stylexjs/stylex"

/** Select parts; attribute-driven Base UI states are scoped in primitives.css. */
export const styles = stylex.create({
  group: { scrollMarginBlock: 4, padding: 4 },
  value: { display: "flex", flex: 1, textAlign: "start" },
  trigger: {
    display: "flex",
    width: "fit-content",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--input)",
    backgroundColor: "transparent",
    paddingBlock: 8,
    paddingInlineEnd: 8,
    paddingInlineStart: 10,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    whiteSpace: "nowrap",
    outline: "none",
    userSelect: "none",
    transitionProperty: "color, background-color, border-color, box-shadow",
    transitionDuration: "150ms",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  chevron: { pointerEvents: "none", width: 16, height: 16, color: "var(--muted-foreground)" },
  positioner: { isolation: "isolate", zIndex: 50 },
  popup: {
    position: "relative",
    isolation: "isolate",
    zIndex: 50,
    maxHeight: "var(--available-height)",
    width: "var(--anchor-width)",
    minWidth: 144,
    transformOrigin: "var(--transform-origin)",
    overflowX: "hidden",
    overflowY: "auto",
    borderRadius: 8,
    backgroundColor: "var(--popover)",
    color: "var(--popover-foreground)",
    boxShadow:
      "0 0 0 1px color-mix(in oklab, var(--foreground) 10%, transparent), 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
  },
  label: {
    paddingInline: 6,
    paddingBlock: 4,
    fontSize: "0.75rem",
    lineHeight: "1rem",
    color: "var(--muted-foreground)",
  },
  item: {
    position: "relative",
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    gap: 6,
    borderRadius: "var(--radius)",
    paddingBlock: 4,
    paddingInlineEnd: 32,
    paddingInlineStart: 6,
    fontSize: "0.875rem",
    lineHeight: "1.25rem",
    outline: "2px solid transparent",
    outlineOffset: 2,
    userSelect: "none",
  },
  itemText: { display: "flex", flex: 1, flexShrink: 0, gap: 8, whiteSpace: "nowrap" },
  indicator: {
    pointerEvents: "none",
    position: "absolute",
    insetInlineEnd: 8,
    display: "flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  check: { pointerEvents: "none" },
  separator: {
    pointerEvents: "none",
    marginInline: -4,
    marginBlock: 4,
    height: 1,
    backgroundColor: "var(--border)",
  },
  scrollUp: {
    top: 0,
    zIndex: 10,
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--popover)",
    paddingBlock: 4,
  },
  scrollDown: {
    bottom: 0,
    zIndex: 10,
    display: "flex",
    width: "100%",
    cursor: "default",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--popover)",
    paddingBlock: 4,
  },
})
