// Generated by Cypress Author on 2026-08-31.

describe("Prime Agent first session", () => {
  it("creates a real session from the empty Zenbu workspace", () => {
    cy.env(["rendererUrl"], { log: false }).then(({ rendererUrl }) => {
      if (typeof rendererUrl !== "string" || rendererUrl.length === 0) {
        throw new Error("The Electron launcher did not provide a renderer URL")
      }
      return cy.visit(rendererUrl, { log: false })
    })
    cy.get("#empty-state-prompt").should("be.visible").type("Reply with ready")
    cy.get('[data-cy="prime-empty-create"]').should("be.enabled")
    cy.task("seedPersistedPrimeAgentSession", null, { log: false })
    cy.reload()

    cy.get("#chat-message")
      .should("exist")
      .should("be.enabled")

    cy.get('[data-zenbu-view="app/sidebar"] button[aria-current="page"]')
      .should("be.visible")
      .and("contain.text", "New Prime Agent session")

  })
})
