// Generated by Cypress Author on 2026-08-31.

describe("Prime Agent first session", () => {
  it("creates a real session from the empty Zenbu workspace", () => {
    cy.env(["rendererUrl"], { log: false }).then(({ rendererUrl }) => {
      if (typeof rendererUrl !== "string" || rendererUrl.length === 0) {
        throw new Error("The Electron launcher did not provide a renderer URL")
      }
      return cy.visit(rendererUrl, { log: false })
    })
    cy.contains("h2", "Start a conversation").should("be.visible")
    cy.get('[data-cy="prime-empty-create"]').should("be.enabled").click()

    cy.contains("h1", "New Prime Agent session", { timeout: 75_000 }).should("be.visible")
    cy.get("#chat-message")
      .should("be.enabled")
      .and("have.attr", "placeholder", "Ask Prime Agent to build something...")

    cy.get('[data-zenbu-view="app/sidebar"] button[aria-current="page"]')
      .should("be.visible")
      .and("contain.text", "New Prime Agent session")
  })
})
