describe("Update controls with an isolated transport", () => {
  it("checks, offers an update, and applies only after interaction", () => {
    cy.visit("/?browser=1&scenario=updates")
    cy.contains("button", "Check for updates").click()
    cy.contains("Ernie 0.1.1 is available.").should("be.visible")
    cy.contains("Apply requests: 0").should("be.visible")
    cy.contains("button", "Update…").click()
    cy.contains("Apply requests: 1").should("be.visible")
    cy.contains("Restarting Ernie…").should("be.visible")
  })
  it("shows a failed check and allows recovery", () => {
    cy.visit("/?browser=1&scenario=updates")
    cy.contains("label", "Reject checks").find("input").check()
    cy.contains("button", "Check for updates").click()
    cy.contains("Download unavailable. Try again.").should("be.visible")
    cy.contains("label", "Reject checks").find("input").uncheck()
    cy.contains("button", "Check for updates").click()
    cy.contains("Ernie 0.1.1 is available.").should("be.visible")
  })
  it("acknowledges actions while slow transport work is still pending", () => {
    cy.visit("/?browser=1&scenario=updates")
    cy.contains("label", "Slow responses").find("input").check()
    cy.contains("button", "Check for updates").click()
    cy.contains("Checking for updates…", { timeout: 300 }).should("be.visible")
    cy.contains("Ernie 0.1.1 is available.").should("be.visible")
    cy.contains("button", "Update…").click()
    cy.contains("Preparing update…", { timeout: 300 }).should("be.visible")
    cy.contains("Apply requests: 0").should("be.visible")
    cy.contains("Apply requests: 1").should("be.visible")
  })

  it("receives background events without idle polling and refreshes on focus", () => {
    cy.visit("/?browser=1&scenario=updates")
    cy.contains("Status reads: 1").should("be.visible")
    cy.clock()
    cy.tick(60_000)
    cy.contains("Status reads: 1").should("be.visible")
    cy.contains("button", "Background update").click()
    cy.contains("Ernie 0.1.1 is available.").should("be.visible")
    cy.window().invoke("dispatchEvent", new Event("focus"))
    cy.contains("Status reads: 2").should("be.visible")
  })
})
