[workspace]
resolver = "2"
members = ["crates/desktop", "crates/plugin-runtime", "crates/ui"]
default-members = ["crates/desktop"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.95"

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "101ca00a1352ed71ef398f21b47836565d1998e3" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "101ca00a1352ed71ef398f21b47836565d1998e3" }
ernie-gpui-ui = { path = "crates/ui" }
ernie-plugin-runtime = { path = "crates/plugin-runtime" }

[workspace.lints.rust]
unsafe_code = "forbid"
